### ISSUE TITLE
Question about AVTs and QName-magic

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#1001]
Not sure this is right, so pointing out my mistake to me would help.
Consider:
````
<p:wrap-sequence wrapper="wrapper" />
````

[Section 10.1.](https://spec.xproc.org/master/head/xproc/#attribute-value-templates) says:

> The value of an attribute that contains attribute value templates is a single string (the concatenation of the string values of the evaluated templates and non-template parts) as an xs:untypedAtomic.

So: The value of $wrapper is xs:untypedAtomic. Right?

But the option `wrapper`on `p:wrap-sequence` is declared as `xs:QName` so this is the place, where "[QName handling](https://spec.xproc.org/master/head/xproc/#qname-handling)" has to come in. But QName handling is only defined for xs:string -> xs:QName, not for xs:untypedAtomic -> xs:QName.

Therefor the above snippet `p:wrap-sequence` has to raise an error [XD0068](https://spec.xproc.org/master/head/xproc/#err.D0068). Right?

Could somebody please tell we, why I am wrong? What did I miss?

**Comment by gimsieke** [comment]
Hmm, I don’t currently know why AVTs result in xs:untypedAtomic instead of xs:string, but there are probably reasons for this. Maybe xs:untypedAtomic is castable without friction when the required attribute type is xs:integer, for example.

Anyway, what seems to be missing in [QName handling](https://spec.xproc.org/master/head/xproc/#qname-handling) is this:

> 2. If the value supplied for the option is an instance of `xs:string` (or a type derived from `xs:string`, _or a type castable as `xs:string`_), …

As it is specified now, I think you are right in assuming that XD0068 must be raised. Unless I’m missing something.

**Comment by ndw** [comment]
Yes, that seems like it would cover the case. I think we do *want* QName magic to apply to AVTs in option shortcuts.

**Comment by ndw** [comment]
15 July 2021, editors agree to attempt to make "QName magic" work here.

**Comment by gimsieke** [comment]
Here’s a proposal to rebrand QName (and related) magics as “implicit typecasting” in order to soften the derogatory aspects of it.

**Comment by gimsieke** [comment]
A related magic that can be called _implicit typecast_ is the `xs:string` → `xs:anyURI` casting prompted by #1012
