### ISSUE TITLE
Possible contradiction in the specs?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#1006]
I am a bit confused by two statements in the specs, which seem to contradict:

1. On [Syntactic Shortcut for Option Values](https://spec.xproc.org/lastcall-2020-08/head/xproc/#option-shortcut) it is said:

> For any other option’s sequence type it is considered an attribute value template. [...] The attribute’s string value, after the attribute value template expansion, is used as the value of the option. It must be possible to convert this string to the option’s sequence type."

2. On [Attribute value templates](https://spec.xproc.org/lastcall-2020-08/head/xproc/#dt-attribute-value-template) it says:

> The value of an attribute that contains attribute value templates is a single string (the concatenation of the string values of the evaluated templates and non-template parts) as an xs:untypedAtomic.

To my reading these two quotes apply both to the case where an option value is assign via syntactic short cut. But the first seems to say, that the value is a string (that must be castable to the required sequence type) while the second quote says it is an instance of xs:untypedAtomic.

Do I miss something?

**Comment by xatapult** [comment]
Good catch. I would prefer the approach of statement #1. 

It's how I think about AVTs: They expand into a string that is then converted into the sequence type of the option.

**Comment by ndw** [comment]
> I am a bit confused by two statements in the specs, which seem to contradict:

I think the two statements are supposed to say the same thing. I think
the description under syntactic shortcuts should be redrafted:

  As with other attribute value templates, the attribute’s string value,
  as an xs:untypedAtomic, is used as the value of the option. Normal
  conversion rules apply to convert this untyped atomic value to the
  option’s sequence type.

> To my reading these two quotes apply both to the case where an option
> value is assign via syntactic short cut. But the first seems to say,
> that the value is a string (that must be castable to the required
> sequence type) while the second quote says it is an instance of
> xs:untypedAtomic.

I don’t think “it must be possible to convert this string to the
option’s sequence type” means you can apply casting. I don’t think the
processor can ever silently cast values because “3.1 cast as xs:integer”
is the integer “3” and that’s really not something the processor should
do without being asked explicitly.

I think “it must be possible to convert this string to the option’s
sequence type” is actually meant to imply that if it *can’t* be
converted using the normal conversion rules, a type error will be
raised.

If an option is of type xs:date,

  <ex:mystep date-option=”{current-date()}”/>

is never going to work and there’s nothing we can do about that, AFAICT.

:-(

                                        Be seeing you,
                                          norm

--
Norman Tovey-Walsh ***@***.***>
https://nwalsh.com/

> "Abstraction, abstraction and abstraction." This is the answer to the
> question, "What are the three most important words in
> programming?"--Paul Hudak

**Comment by ndw** [comment]
I was wrong about converting to dates from untyped atomic. And this has been fixed in the spec.
