### ISSUE TITLE
Error in example?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#1012]
In section [7.2.2. XPath in XProc](https://spec.xproc.org/lastcall-2020-08/head/xproc/#xpath-context) the code example uses:
````
<p:load name="read-from-home">
  <p:with-option name="href" select="concat($home,'/document.xml')"/>
</p:load>
````
I would argue that this should fail with XD0036 because `select` returns an xs:string, but `href` requires an xs:anyURI. As function conversion rules apply here, the xs:string cannot be converted to xs:anyURI. Hence the error.
The example is a verbatim copy of the one used in XProc 1.0 specification, so I guess that is the reason for this problem.
Did I miss something?

**Comment by ndw** [comment]
Mmm. I expect the expectation was that that would work because `xs:anyURI` is a kind of string. But it doesn't work in that direction, of course. Yes, that's an error in the spec. I don't remember what 7.2.2 is about (and it's not convenient to look just at the moment), but we could fix that either by saying:
```
<p:load name="read-from-home" href="concat($home, '/document.xml')"/>
```
(or even `href="$home||'/document.xml'"`), because shortcuts are `xs:untypedAtomic` values so the cast will work. Or by saying:
```
p:load name="read-from-home">
  <p:with-option name="href" select="xs:anyURI(concat($home,'/document.xml'))"/>
</p:load>
```

**Comment by xatapult** [comment]
Yes, formally speaking it is correct: You have to pass in a value as an `xs:anyURI`.

But... I know this situation from eXist. There some functions also have `xs:anyURI` types arguments. That always leads to situations where you do string manipulation to get to the right filename (as in the examples above) and, just for the sake of the function, add an `xs:anyURI(...)` around it. So the fact that the argument is of type `xs:anyURI` is more a nuisance than useful.

I do agree that typing these arguments as `xs:anyURI` adds value because its now clear you have to pass in a URI, but for the programmer it only leads to annoying `xs:anyURI(...)` calls that add no real value.

Can't we do something that auto-converts strings into `xs:anyURI` in these cases? Maybe something like we did like the QName magic?

**Comment by ndw** [comment]
15 July 2021, editors wish to explore the possibility of automagically casting `xs:string` values to `xs:anyURI` in this case. A kind of magic analogous to the "QName magic" we apply elsewhere. Norm to discuss with Achim.
