### ISSUE TITLE
Default inputs

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1029]
In 16.1, we say:

> On a `p:declare-step` for an atomic step, the `p:input` can only declare the input port. It is a static error (err:XS0042) to attempt to provide a connection for an input port on the declaration of an atomic step.

I don't think that's true. It's certainly at odds with this declaration:

```
<p:declare-step type="p:archive">
     <p:input port="source" primary="true" content-types="any" sequence="true"/>
     <p:input port="manifest" content-types="xml" sequence="true">
          <p:empty/>
     </p:input>
     ...
```

Which of the following is the best explanation for this apparent discrepancy:

1. It's fine, I'm just confused about what it means.
2. It used to be this way, but we changed our minds and decided to allow them, so this error should be removed.
3. The error is actually meant to say something else about the bindings.

**Comment by xatapult** [comment]
Or:
4. Only allow `<p:empty/>` for atomic steps

???

**Comment by gimsieke** [comment]
Does “atomic step“ above pertain only to “processor-provided atomic steps” (see [§ 15.8](https://spec.xproc.org/master/head/xproc/#p.atomic))?

**Comment by ndw** [comment]
I don't think it matters who provides the atomic step.

I see the appeal of saying that only `<p:empty/>` is allowed, but that would make the bindings different between atomic and non-atomic steps and that just seems like it could be confusing.

**Comment by gimsieke** [comment]
We use default inputs in declarations for atomic steps all the time, take [docx2hub.xpl](https://github.com/transpect/docx2hub/blob/master/xpl/docx2hub.xpl#L29) as an example. Why would we want to make this illegal in 3.0?

I suspect the error above is a consequence of inconsistent use of “atomic step” in the 1.0 spec. 

There is a distinction between atomic steps (no subpipeline in their declarations) and extension steps (subpipelines in their declarations) in [4.7 Atomic Steps](https://www.w3.org/TR/xproc/#p.atomic) and [4.8 Extension Steps](https://www.w3.org/TR/xproc/#p.extension), respectively. The 4.7 kind of thing (declaration w/o subpipeline) is probably what `err:XS0042` is referring to. 

Similarly, [`errXS0029` in the 1.0 spec](https://www.w3.org/TR/xproc/#err.inline.S0029) says that atomic steps must not provide a connection in `p:output`. 

[5.8.1 Declaring atomic steps](https://www.w3.org/TR/xproc/#declare-atomic-steps) says:

> When declaring an atomic step, the subpipeline in the declaration must be empty. And, conversely, if the subpipeline in a declaration is empty, the declaration must be for an atomic step.

The [glossary](https://www.w3.org/TR/xproc/#glossary), on the other hand, only says this about atomic steps:

> An atomic step is a step that performs a unit of XML processing, such as XInclude or transformation, and has no internal subpipeline.

If I declare my own step in XProc, it will have a subpipeline in its declaration. But never when it’s called.

This is more in line with the definition of an atomic step as given in [2.1 Steps](https://www.w3.org/TR/xproc/#step-concept):

> [Definition: An atomic step is a step that performs a unit of XML processing, such as XInclude or transformation, and has no internal subpipeline.] Atomic steps carry out fundamental XML operations and can perform arbitrary amounts of computation, but they are indivisible. An XSLT step, for example, performs XSLT processing; a Validate with XML Schema step validates one input with respect to some set of XML Schemas, etc.

According to 2.1, the usual self-declared steps that use `p:declare-step` and subpipelines are atomic steps Their invocations, however, must not have a subpipeline. 

It is admissible and common that they have default bindings for their input ports. Not just `p:empty`, but also `p:document`.

Do you see that there are two conflicting definitions for atomic steps in the 1.0 specification? According to 5.8.1, their declarations must not contain subpipelines. According to 2.1, only their ivocations must not contain subpipelines.

Are self-defined steps like `my:transform-n-validate` atomic? According to 2.1, they are. They perform atomic operations and do not accept a subpipeline when invoked. According to 5.8.1, they aren’t, because their declaration contains a subpipeline.

`err:XS0042` only pertains to 5.8.1-style atomic steps, not necessarily to any kind of 2.1-style atomic steps.

In 3.0, we adopted the 2.1-style definition in [§ 15.8 Atomic Steps](https://spec.xproc.org/master/head/xproc/#p.atomic):

> [Definition: An atomic step is a step that does not contain a subpipline when it is invoked.]

So the unchanged error `err:XS0042` that pertains to a 5.8.1-style atomic step does not apply here. It only applies to atomic steps whose declaration doesn’t contain a subpipeline, I guess.

So you are right, it’s not about whether the processor provides the atomic step but whether its declaration has a subpipeline. My hypothesis is: Only steps with subpipelines in their _declaration_ may also feature default connections in their declaration.

**Comment by ndw** [comment]
For the record, I'm not trying to make anything illegal in 3.0. If the error applies to "atomic steps whose declaration doesn't contain a subpipline", then the current step declaration for `p:archive` is invalid and I don't think we want that.

Proposal: remove `err:XS0042` as there is no condition under which it applies.

**Comment by gimsieke** [comment]
I should have read more closely what you wrote above. I didn’t look at the current declaration of `p:archive`. 

Then we might permit `p:empty` (not `p:document` though) in declarations without subpipeline. 

But we need to get the use of “atomic step“ consistent. Apart from `err:XS0042`, `err:XS0029` has survived unchanged from 1.0, and its assumed definition for “atomic step” (step without a subpipeline in its declaration) is at odd with the definition of atomic step (step without a subpipeline in its invocation). I’ll raise a different issue for that.

**Comment by ndw** [comment]
Why forbid `p:document` and `p:inline` in this case but not the other case? From my perspective the cases are the same, I think the rules should be the same. What am I missing?

**Comment by gimsieke** [comment]
I was just a bit conservative, along the lines of “they must have had a reason to forbid default connections for these steps, so let’s only permit the one that’s currently making `p:archive` illegal.”

What might have been the rationale for this rule?

One reason to disallow `p:document` default connections is that the document specified in `@href` might not be available when the step runs. But that’s not a strong enough reason to disallow it. Maybe the processor that runs the step also knows how to resolve that URI.

So I’m not against removing `err:XS0042` entirely (and possibly amending the grammar accordingly).

What should we do the about `err:XS0029`?

**Comment by ndw** [comment]
I think we should leave `err:XS0029` as it is. The processor can know by inspecting the pipeline if a step is going to have (or potentially have) any inputs and use the defaults if it is not. The processor has no corresponding way to know if the step is going to produce any output. We have no use case for it, we can fix it in V4 if there's a need.
