### ISSUE TITLE
Think about "p:type-switch"

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#109]
In XProc 3.0 every document is a pair of a representation and its properties. One important property is "content-type" which hold the media-type of the representation.

I expect it to be a common use case to process documents depending on their content-type. This can be done with p:choose, making decisions on the value return by p:document-properties('content-type'), but we might think about having a shortcut for this as an analogy for [type-switch in XQuery 3.1](https://www.w3.org/TR/xquery-31/#id-typeswitch).

Example:
```
<p:type-switch>
    <p:case content-type="application/xml">
      ...
   </p:case>
   <p:case content-type="image/jpeg">
      ...
   </p:case>
   <p:otherwise>
      ...
   </p:otherwise>
</p:type-switch>
```
Note: I do not like the name 'type-switch' because it might suggest a _change of type_. But it is used in XQuery, so may be familiar to XProc users. When we can come up with a better element name, I will be happy with this.

**Comment by Conal-Tuohy** [comment]
To me this seems like too narrow a use case to justify adding semantic sugar. I'd be more favourable to a generalised "switch" statement which could switch on any string value. e.g. for switching on content-types:

```xml
<p:switch select="p:document-properties('content-type')">
   <p:case value="application/xml">

   </p:case>
   <p:case value="image/jpeg">

   </p:case>
   <p:otherwise>

   </p:otherwise>
</p:type-switch>
```

**Comment by xml-project** [comment]
Good point!
But content-types are not exactly like strings: Think of "content-type='application/*+xml" or "content-type='image/*'. 
May be I was to short about this: The subpipeline of "case" is executed, when the content-type attribute of the document **matches** the value of "content-type", I did not think of "fn:compare(xs:string, xs:string)".

**Comment by gimsieke** [comment]
I agree with Conal that the proposed `p:type-switch` won’t probably be used very often outside the unzip result processing example. And I think that the field of application for a `p:switch` might be served well enough by `p:choose`, albeit its XPath expressions are a bit more repetetive. On the other hand, I liked someone’s proposal for introducing `p:if` as a shortcut for a 1-pronged `p:choose` (or one with an implicit `p:otherwise/p:identity`). I don’t know what is the right balance between the goals of offering terseness of expression to pipeline authors on the one hand and curbing “vocabulary sprawl” on the other hand. You could argue that the former is a stated goal of our current initiative while the later isn’t, so let’s coat everything with syntactic sugar ;)
