### ISSUE TITLE
Semantic of @depends

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#127]
The current text of the specs says, that a step A that has "depends='B'" is guaranteed to be run after the step on which it depends.

Now suppose B is part of the subpipeline of p:for-each or p:viewport while A is not: Is A guaranteed to be run after the first run of B or after the last run?

Possible solution: The step named in attribute 'depends' is required to be a sibling of the step on which the attribute is used. In the above case: A needs to depend on the p:for-each, so the problem does not arise.

**Comment by gimsieke** [comment]
If A is not part of the subpipeline of which B is part of: Then A can’t depend on B anyway because B is out of scope for A, isn’t it? Scoping of step names is already well-defined in the paragraph after [this one](http://spec.xproc.org/master/head/xproc30/#scoping.8.1.1).

This can happen:
```xml
<p:store name="B"/>
<p:for-each>
  <p:input>
    <p:pipe port="docs" step="C"/>
  </p:input>
  <p:do-something name="A" depends="B"/>
</p:for-each>
```

This can’t (as per current scoping rules):
```xml
<p:for-each>
  <p:input>
    <p:pipe port="docs" step="C"/>
  </p:input>
  <p:do-something name="B"/>
</p:for-each>
<p:identity name="A" depends="B"/>
```

**Comment by ndw** [comment]
I believe that @gimsieke is correct.

**Comment by xml-project** [comment]
Thank you two: Of course I should have looked at the scoping rules. My fault!
