### ISSUE TITLE
What about that document-properties attribute?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#133]
For discussion please see: http://markmail.org/message/bxfpqnwvym5v7yhc?q=xproc-dev

**Comment by ndw** [comment]
Document properties is explicitly a map from strings to strings. Should we make it an error if the specified key or value is not a string?

I'm inclined to say yes because if we allow non-strings, users may get odd errors. Consider this example:

````
   <p:inline document-properties="{ map {{ 'a': 1 }} }"> ... </p:inline>
   ...
   <p:choose>
      <p:when test="p:document-properties(., 'a') = 1"> ...
````

On first glance, you might think that would work. But in fact, you'll get an error because strings and integers aren't comparable and the document property value has (in this implementation :-) )  been coerced to string.

Alternatively, we could say that document-properties is a map from string to atomic values.

**Comment by xml-project** [comment]
Yes, it should be an error. As @document-properties is defined as "map (xs:string, xs:string)" I would expected an XPath error (XPTY0004) when the value is assigned.

Defining document-properties as map(xs:string, xs:anyAtomicType) may be the better idea because we  can avoid conversions for user defined properties.

**Comment by gimsieke** [comment]
I, too, think that xs:anyAtomicType can help avoid the need for explicit or implicit casting down the line. But then we need to check that the values of certain known document properties (content-type should be an xs:string, base-uri should be an xs:anyURI, …) are in fact of the required type. In addition, [standard casting rules](https://www.w3.org/TR/xpath-functions-3/#casting-from-primitive-to-primitive) should apply when, for example, someone attempts to assign a string value (that happens to be castable to xs:anyURI) to the base-uri property.

**Comment by xml-project** [comment]
As per Aachen workshop we decided that document-properties are map{xs:QName, item()}

**Comment by ndw** [comment]
I believe this is done.
