### ISSUE TITLE
Treat the `parameters` option specially?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#197]
I'm on the fence about this one. Consider:

    <p:load parameters="{ map {{ 'liberal': true }} }" href="file.json"/>

That's kind of tedious and `parameters` *has to be* an expression, there's no string value that you can put in there except an expression. So, like `document-properties`, it might be convenient to say that it is always an expression. That would also mean that it could just be an expression on `p:document` (see #196) where it *isn't* an option.

But on steps, *it is* just an "ordinary" option, so treating it specially is an exception that authors will have to remember.

I think, on balance, the exception is going to be less annoying than the AVT. But I'm not sure.

**Comment by xml-project** [comment]
I am not sure I got your point. If think you would like to to write (as I do):
`<p:load parameters="map{'liberal'.true}" ...`

Is the double brackets the problem? You could escape this by using a variable, but that is probably not a good reason.
What is you proposal?

**Comment by xml-project** [comment]
OK, after some thinking, I got your point and I agree .... , well almost.

I do not like the exception for "parameters", because it is hard to remember. And: As you said, for an option with type map() or array() it NEVER makes sense to have a string value in the option short-cut notation.

So let us make a general rule: 
For every step: If an option is declared with type "map()" or type "array()", the option short-cut is an expression, so you do not need curly brackets there.

Now it applies to all steps in the step library to have option of type map (e.g. p:store, p:xslt ...) and it also applies to all steps defined via 'p:declare-step'.

**Comment by ndw** [comment]
The value of the parameters option, as you've written it, is syntactically invalid. You've written the word "map" followed by an expression in an attribute value template: "'liberal'":true" (I assume the "." instead of ":" in your example is a typo) which is not a syntactically valid XPath expression.

As it stands today, you *have* to write

    <p:load parameters="{ map {{ 'liberal': true() }} }" ...

And if you wanted to use a variable, you'd still need the AVT: `"{$map}"`.

My proposal is to say that the option named "parameters" should always be treated as if it was an expression, not an AVT.

**Comment by ndw** [comment]
The idea of basing it on the type is interesting. I wonder if that's going to be more or less confusing. I think I like it, but I'll have to think about it some more.
