### ISSUE TITLE
Nodes as a result of a TVT

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#213]
Unlike in XSLT in XProc 3.0 the evaluation of text value template may produces may, for example if a variable holding nodes is used or if a function is used, which return nodes.

This is fine, but the current version of the specs leaves two cases out:

Case 1: if the node is an attribute, what will happen?
(1) the attribute is added to the "nearest" element node,
(2) the string value of the attribute is added as text node,
(3) a dynamic error is raised.

Case 2: if the node is a document node, what should happen?
(4) All children of the node are inserted,
(5) an error is raised.

Proposal: I would argue to raise an error in both cases, but I am also open for solution (3) and (4).

**Comment by ndw** [comment]
I propose:

Case 1: If the immediately preceding sibling is a start tag, then add the attribute to that element, otherwise error. So `<foo>{$attr}</foo>` is ok. So is `<foo>{$attr1}{$attr2}</foo>` but `<foo>Hello {$attr}</foo>` is an error.

Case 2: Insert all the children.

**Comment by xml-project** [comment]
I agree to "insert all children" in case two.

For case 1: What about <foo>{$att1}{$att2}</foo>?

The first ok (because it immediately follows), but the second not, because it follows {$att1}. If we really want to allow to add calculated attributes, we should take all.

**Comment by xml-project** [comment]
As far as I can see, there is no guarantee that an XPath expression in a TVT evaluates to a single value. It might be a sequence as well, right?
So the prose for attribute case turn out to be complicated, because $attr may contain a mixed sequence of attributes followed by text and in this case
<foo>{$attr}{$attr2}</foo>
should be an error. Agreed?

**Comment by ndw** [comment]
Yes. Ultimately, in tree terms, an attribute can be added if and only if its parent is an element and it has no preceding siblings (or no preceding siblings that are not attribute or namespace nodes, depending on how you do tree construction).

**Comment by xml-project** [comment]
Ok, thats my reading too. 
I will try to make some prose of it (hopefully avoiding the tree terminology).

**Comment by xml-project** [comment]
After thinking about it: Do we really need to say that `<foo>Hello {$attr}</foo>` is an error? To my reading it is perfectly clear what the developer want to do and it is (at least to my reading) in no way ambiguous. 
The only case I would suggest to result in an error, if I try to add an attribute to the element, whose name is equal to the name of an attribute already present.
What did I miss?

**Comment by ndw** [comment]
Depends what you mean by clear. Assuming that `$attr` is an *attribute node*:

1. You could think that means put `$attr` on `<foo>`, that would be inconsistent with XSLT and XQuery and would, in some implementations, be very difficult to implement. If I'm constructing the tree as I go, once I've started outputting text nodes, it may not be possible to "go back" and put an attribute on the start node.
2. If you think that it means output the string value of the attribute, then the author can make that explicit with `{string($attr)}` which is unambiguous.

I favor making it an error because about half the time I get surprised that this expression (in XQuery)

    <foo> { $element/@attribute } ... </foo>

sticks the attribute on `foo`. (The other half of the time, that's what I'm explicitly trying to do.) I agree that it should and I agree that's what I'm proposing for XProc, but if that sticks the attribute on `foo` and this:

    <foo>some text {$element/@attribute} ... </foo>

puts the text value of the attribute in the content of `foo`, I'm going to find the "copy attributes" behavior both surprising *and* inconsistent.

**Comment by xml-project** [comment]
Yes, you are right. I did not see the case that {$element/@attribute} might be an attempt to add the text value of @attribute to the element. It is ambiguous, so we should raise an error.

**Comment by gimsieke** [comment]
I concur with https://github.com/xproc/3.0-specification/issues/213#issuecomment-337236476

**Comment by xml-project** [comment]
Fixed with pr #222
