### ISSUE TITLE
static and dynamic XPaths errors in AVT/TVT

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#217]
The specs says:
"It is a static error if the string contained between matching curly brackets in a value template, when interpreted as an XPath expression, contains errors. The error is signaled using the appropriate XPath error code." (Section 2.10.)

We should spell out in detail, which errors are statically handled: We could do crude syntax errors only but do we also check variable binding, reference to the context node, type checking or available functions?
And if we do static checking with AVTs I think it is obvious to do it also on p:with-option and attributes on XProc elements.

I am strongly in favour of more static checking (which is possible in XProc 3.0) because it makes XProc a safer language.

**Comment by ndw** [comment]
If it isn't already in the spec, we should add "an implementation is free to detect and report statically any dynamic error that is guaranteed to occur at runtime"

**Comment by xml-project** [comment]
Yes, that seems to be a good point: The error can be detected statically and the error code for the dynamic error is used. But I think this is only have way of the journey.
An XProc 1.0 pipeline may contain error that are never raised i.e. they are in p:when's never executed. In these cases a pipeline might run perfectly on one processor (because the error in never raised) and fail on another processor. 
I guess the problem is the term "guaranteed". Since it is in most cases impossible to say statically which p:when will be executed: Is is "guaranteed to occur at runtime" or not?
May be we do not need the all in one approach but mark cases, where a static checking has to be done (e.g. reference to a missing value in an XPath expression) and other cases, where the implementation is free to do it. 
To ensure interoperability in those cases it can only be a hint to developers what MIGHT happen if something other happens, but not an error, unless the step is actually executed.
I am not sure, whether this is something developers care about or whether they are used to the lazy style of XProc 1.0. Maybe @gimsieke should set up another survey ;-))

**Comment by ndw** [comment]
A few thoughts. First, there's nothing that prevents an implementation from warning about problems that might occur. And it's something of a quality of implementation issue if they fail on conditions that they should not fail on. However, at the end of the day, I think this is a problem common to all programming languages. If I write

    if (false) then { 1 div 0 }

I expect my program to compile and run without error because that division-by-zero expression will never be evaluated. The same is true of `p:when` branches. If a `p:when` contains an expression that will cause a dynamic error, then I think it should only be raised statically if the implementation can work out statically that that branch will *always* be selected. There are trivial cases (the first `p:when` has a test that's `"true()"` for example) and there are more complicated cases; how much effort an implementor wants to put into static analysis is outside the scope of the spec.

With respect to "might run perfectly on one processor and fail on another", I'm not sure how that could happen unless the `test` expression in the `p:when` was testing for the processor implementation. In which case, yes, it could, and that's what the author asked for.

**Comment by xml-project** [comment]
I agree that there is a continuum. But XProc 1.0 was in some respects far on one side, for example because you have an undeclared variable in an XPath expression in some p:when never executed (yet)! And I try to argue for for these obvious cases every programmer coming from Java etc. would expect a static error to be raised.

>  `With respect to "might run perfectly on one processor and fail on another", I'm not sure how that could happen unless the test expression in the p:when was testing for the processor implementation. In which case, yes, it could, and that's what the author asked for.`

This might happen if we take the "implementation defined" interpretation to far because one processor raises a detected error when dynamic execution begins and the other one never raises this error because the step causing the error is not executed (yet).

**Comment by ndw** [comment]
I don't think processors should raise errors statically for dynamic errors that might not occur. So I think in the latter case, the implementation raising the error is non-conformant.

I understand the advantages of static typing and error detection. Consider:

    <p:choose>
      <p:when test="true()">
        <p:identity/>
      </p:when>
      <p:when test="$a gt; 5">
        <p:if test="ex:fred(.)">
          <ex:whatever/>
        </p:if>
      </p:when>
    </p:choose>

Suppose that `$a` is not defined and there is no context node. There are two schools of thought here, one is that you should raise those errors, they will *clearly* occur *if* the expression is evaluated. The other school of thought is: they will *never* be evaluated, so it's incorrect to raise an error.

In defense of the latter case, imagine that I'm refactoring a complicated bit of code, or porting over a step from some other pipeline. Perhaps I'm doing it in stages and I haven't got around to declaring those variables or establishing the context. You're going to prevent me from taking an iterative approach, or require me to comment out a bunch of code, to avoid an error that *will not* occur? That seems...like a bad idea.

I'm wholly in favor of a switch on the implementation that says "check all my errors, there aren't supposed to be any anywhere" but I'm not sure I want that to be the conformant behavior.

**Comment by xml-project** [comment]
In principal I would take side with school A: Do not run my software if you know (or could know) that something MIGHT happen.

But I am not arguing for this case. I just try to explore how much static checking we will do so we can prevent that we have a school A and a school B processor in the wild. Imagine someone trying to learn XProc 3.0 and starting her pipeline on both processors. I would guess that we will loose her after 15 minutes.

So coming back to the starting point of your suggestion:

> If it isn't already in the spec, we should add "an implementation is free to detect and report statically any dynamic error that is guaranteed to occur at runtime"

I would suggest to say:
"An implementation must report all static errors in a pipeline and must not start the pipeline if any static error is encountered. An implementation may report statically any dynamic error that may occur at runtime but it may not raise any of these errors before the step causing the error is actually executed."

I do not insists on the wording and I would accept any suggestion. But I think we should make this case clear. Finding nothing about it in XProc 1.0 was a great hurdle for my implementation. The only guiding I had came from the test suite. And I do not think, developers of XProc pipelines should be required to consult the test suite to understand the behaviour of their pipelines.

**Comment by xml-project** [comment]
By the way:
 Is this just a point, @ndw and I are interested in or is no one else online and/or awake?

**Comment by ndw** [comment]
I don't understand your suggestion. If "it may not raise the errors before the step causing the error is actually executed" then it's not reporting the error statically.

**Comment by xml-project** [comment]
I am sorry. I tried to find a formulation that is abstract enough to cover more cases, but may be this is the wrong way to do it.

What I had in mind is this: Suppose I have an XPath expression referring to a variable that is not declared. In XProc 1.0 that was a dynamic error and I guess it will be a dynamic error in XProc 3.0 too.

However due to the architecture of my implementation I have to parse XPath expressions during static analysis, so I know that this XPath expression will cause a dynamic error if the respective step is executed. If it is not part of a choose or a try, I could even know for sure, what will happen.

And my point was to find a rule for the switch you suggested: I am allowed to inform about the error (that will happen), but I am not allowed to raise this error because it actually happen, i.e. the step is executed.

May be the problem in my formulation is "report the error" (=inform the author at will, that her pipeline is defective) as opposed to "raise the error".

Is this a better way to make my point?

**Comment by ndw** [comment]
I don't think the spec needs to say anything about what informational messages a processor produces. A conformant processor can report the phase of the moon if it wants to.

We all have to parse XPath expressions statically (because of how variables work). I think the formulation "guaranteed to occur" covers the case you outline. A reference to an undeclared variable that is not inside a p:choose or p:try is "guaranteed to occur"[*] so you can report it statically if you wish. You don't have to, of course. Or we could make it a requirement.

[*] Almost guaranteed to occur. I suppose one could argue that a sufficiently lazy implementation might not compute the values of options until they were needed and so, if a step has an option that happens not to be needed, it could have an invalid assignment expression that wouldn't be guaranteed to occur.

FWIW, my implementation isn't that lazy.

**Comment by xml-project** [comment]
I think I completely agree with you, but (with the case you cited in mind), I still think that "guaranteed" to occurs is not precise enough. And we have the explicit distinction between static and dynamic error.  So a developer could expect a pipeline to run, even if it is guaranteed, that is will not terminate successfully. (Think of debugging purposes).
May be we should postpone this point, until the problem actually pops up. I remember that I had to change my implementation of XProc 1.0 because an error I detected statically was a dynamic error in the test-suite. And, as I said before: The test suite should, in my opinion, test the conformance with the specs, and not be an addendum to the specs.

**Comment by ndw** [comment]
I agree about tests. I also want to use markup to make a tighter connection between conformance statements in the spec and tests. Ideally, the tests will find ambiguities in the spec before we release rather than after!

I'm happy to leave the static/dynamic question for a bit. I'll just say that I think a debugging switch that runs the processor in some non-conformant fashion is a perfectly reasonable thing for an implementation to do.

**Comment by xml-project** [comment]
After thinking a while about it, I agree with @ndw 's arguments. The main argument is that dynamic errors should be catchable by p:try.
