### ISSUE TITLE
Introduce attribute to control visibility of steps for an imported pipeline

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#239]
Recently I had a p:library with four step declarations, where one is called by the other three, but should not be called directly from an importing step.
To give pipeline author more control I propose an optional additional attribute on p:declare-step which is only relevant when the p:declare-step appears inside a p:library. 
The attribute might be called "visibility" (like in XSLT 3.0) and could take the values "public" or "private". If there is no attribute "visibility" on a p:declare-step the step is visible when the p:library is imported by another step. But if "visibility" is "private" the step is only visible inside the p:library it is declared on.
To align the approach with the same attribute name and values as in XSLT seem reasonable to make the use easier for pipeline authors familiar with XSLT. But we might also think about an attribute named "export" with takes a boolean value.

**Comment by gimsieke** [comment]
I think this is a useful proposal. I cannot judge how easy it will be to implement though. My feeling is that it shouldn’t be that hard for any implementation. Some modifications to the part in the spec that is about [visibility](http://spec.xproc.org/master/head/xproc30/#dt-visible) would be due.
I was briefly considering a different approach: Keep everything in libraries visible, but let the pipeline author (i.e., the user of the library) decide which steps they need, like in Perl’s `use` instruction (for example, `use sigtrap qw(SEGV BUS);`). So you could add an attribute called `steps` to `p:import` that accepts a list of QNames for the steps to be imported (import all steps if the attribute is omitted). 
But this approach solves a different (non-) issue. I think you approach is better because library authors know best which implementation details of their library they want to hide.

**Comment by xml-project** [comment]
@gimsieke Which notation would you prefer? 

- visibility="public | private" or 
- export (xs:boolean)

**Comment by gimsieke** [comment]
visibility

**Comment by ndw** [comment]
I vote for visibility as well.

**Comment by xml-project** [comment]
Thanks. I will prepare some prose to cover this case.

**Comment by xml-project** [comment]
Solved with rp #245
