### ISSUE TITLE
Serialization parameters map should be QName->String

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#268]
It's currently String->String, but that's wrong because processors can have application-specific serialization options that are QNames.

**Comment by eriksiegel** [comment]
I think we are going to have a huge syntax problem when all maps are `map(xs:Qname, item())`. I've done some experimenting and send out a request on the XSL mailing list for clarification. Got a clear answer from Michael Kay. We got it wrong... 👎 

You can *not* write such a map as: `map{ Q{}content-type : 'text/xml' }`

You *must* write this as: `map{ QName((), 'content-type'): 'text/xml' }`

Now that will be a nightmare to write when you have to construct large maps. Have we shot ourselves in the foot with the decision to make the map's keys xs:QNames?

 I do think we need to provide some syntactic sugar for this.... Or deviate from the XPath syntax (shudder)? Or use another map type?

**Comment by eriksiegel** [comment]
Maybe: Add a conversion function from `map(xs:string, xs:string)` to `map(xs:Qname, xs:string)` that interprets the keys as QNames.

Then you can write something like:

`p:convert-map( map{'content-type': 'text/xml'} )`

This function must then also interpret Q{} constructors and namespace prefixes.

**Comment by eriksiegel** [comment]
After some thinking and to make things work: I propose that all our maps become map(xs:untypedAtomic, item()). 

The xs:untypedATomic is to allow both xs:QName and strings (and in this case anything else but that wont be used much if at all). If we need to allow both xs:QName and xs:string, we need their supertype, which is xs:untypedATomic.

Processing as follows:
- When the key is of type xs:QName, than that's the key, simple.
- When it is not an xs:Qname, its value is stringified and interpreted as a QName. 
   - A prefix used must be in scope (when the map is interpreted/used)
   - Anything that cannot be interpreted as a QName (e.g. an integer key) causes a dynamic error
   - The Q{...} syntax should also be supported.

Maybe it gets difficult when you request a map where some keys were generated by the processor (the document properties is the only one I can think of, correct?). I think returning such a map with all keys as strings would greatly simplify processing it. All "standard" keys (like content-type) are in the no-namespace anyway, so that's no problem. Any key a user might have added him/herself would simply be returned in the way the user defined it. 

The way we've now defined the maps would be a nightmare to use because of the syntax. This is, from a user's perspective, IMHO a simple and understandable solution. No idea what this would mean for the implementers.

**Comment by xml-project** [comment]
Yes, I think this is the way to go.

**Comment by xml-project** [comment]
I wonder whether we should add this behavior, which not just applies to serialization, but also in other cases (p:xslt, p:xquery, p:load, p:document) as implicit behavior to the specs or whether we should introduce a function
`p:makeQNameMap(map(xs:untypedAtomic, item()) as map(xs:QName, item())`
to make the conversion explicit.
This would probably be a good compromise between having to type "xs:QName('key')...." for every single parameter/option on one hand and doing to much magic (that is unexpected for XSLT- or XQuery users) on the other hand.

**Comment by ndw** [comment]
Well. I did some experiments. I can't seem to make `xs:untypedAtomic` work. Using XSLT for experimenting:
```xml

**Comment by xml-project** [comment]
XPath 3.1 specs (2.5.5.8 Map Test) says:

> The MapTest map(X, Y) matches any map where the type of every key is an instance of X and the type of every value is an instance of Y.

Since neither 'a' nor xs:QName('a') are instances of xs:untypedAtomic, an error has to be raised.

**We have to switch from xs:untypedAtomic to xs:anyAtomicType:**
````
<xsl:variable name="mymap"
                as="map(xs:anyAtomicType, item())"
                select="map { xs:string('a'): 'b'}"/>
<xsl:variable name="mymap"
                as="map(xs:anyAtomicType, item())"
                select="map { xs:QName('a'): 'b'}"/>
````
work.

**Comment by ndw** [comment]
Brain cramp. Thank you.

Ok. To recap: we're going to use `map(xs:anyAtomicType, item())` and say that the interpretation of string keys is special for maps where we expect QNames. A string w/o a colon is a QName in no namespace; a string w/a colon is resolved relative to the in-scope-namespaces at that point and raise an error if there's no binding for the specified prefix. It's an error if the string is not lexically a QName.

Is that right?

**Comment by ndw** [comment]
Presumably we're also going to say that non-string, non-QName keys are an error.

**Comment by xml-project** [comment]
> A string w/o a colon is a QName in no namespace; 

+1
>a string w/a colon is resolved relative to the in-scope-namespaces at that point and raise an error if there's no binding for the specified prefix.

Do we really need this? We could use "Q{uri}name" instead or additionally.

>It's an error if the string is not lexically a QName.

+1

>Presumably we're also going to say that non-string, non-QName keys are an error.

+1

**Comment by eriksiegel** [comment]
I would vote for both options for what can be in a string key:
- String with colon resolved to in-scope namespace prefixes
- Support the Q{...}name syntax

But I'm not an implementer. Maybe this is difficult to do?

**Comment by eriksiegel** [comment]
And do we trim leading/trailing spaces from a string key, or is having spacing an error? Not extrely important or useful but I think we must define it.

I would think leading/trailing spacing key a string key invalid.

**Comment by xml-project** [comment]
Sorry gentleman, but I am afraid we got it wrong. I think any serialization done by XProc should be in line with [fn:serialize()](https://www.w3.org/TR/xpath-functions-31/#func-serialize) were $param is defined as "map(*)". If we do not want to confuse users, I think the following fragment should work:

````
<p:variable name="serPars" select="map{'indent':true(),'method','xml'}" />
<!-- ... -->
<p:variable name="string" as="xs:string" select="serialize(.,$serPars)" />
<!-- ... -->
<p:store href="some-where">
   <p:with-option name="serialization" select="$serPars" />
</p:store>
````
IMHO this is an argument against any special rules or special behaviour for serialization parameters: If you want to use a QName in a serialization map in XPath, you will have to write
`map{QName('uri','local'):('value', 'value', 'value')}` and I do not see any reason, why this should be different in XProc. Having a special behaviour for QNames as keys (but not for QNames as values), having only items as values instead of sequences (cdata-section-elements is a space separated list in XProc, but a sequence of QNames in XPath) and having our own approach to character-maps (see below) seems more and more odd to me.

**Conclusion: Let's do it, like XPath does!**

BTW: We should do character maps in accordance with fn:serialize(), so we would not need "p:character-map" in XProc, as in
````
serialize('I am a string', map{'use-character-maps': map{'a':'x'}})
````

**Comment by ndw** [comment]
Right. Per #343 and #344, let's just do all of the maps we define as `map(*)`.

I suppose that might allow us to remove `p:character-map`, but I haven't thought it through. It's true that we've conflated all the serialization parameters into a single great big map on `p:output`, so perhaps character maps are just nested deep in there.

**Comment by eriksiegel** [comment]
Now I'm getting confused. I was *very* happy with Norm's comment on how to interpret these maps with regards to the keys being Qnames:

> the interpretation of string keys is special for maps where we expect QNames. A string w/o a colon is a QName in no namespace; a string w/a colon is resolved relative to the in-scope-namespaces at that point and raise an error if there's no binding for the specified prefix. It's an error if the string is not lexically a QName.

So are we abandoning this now? Or not?

**Comment by xml-project** [comment]
> So are we abandoning this now? Or not?

Yes, I am afraid this is my proposal. I think we should have maps with serialization parameters that work with XProc serialization but also are usable when calling XPath function "serialize()". But this prohibits that the string key 'x:y' is taken as a QName resolved by some inscope prefix, while XPath will take it as a literal string.
You may of course say, that XPath got it wrong and we should do it right, but remember: No serialization parameter of XProc or XPath is a QName, they are literal strings. So having the QName shortcuts proposed will come to work only if we need parameters for third party products, e.g. when using produced related features in xsl-formatter.

**Comment by eriksiegel** [comment]
Ok, let me summarize to see if we're all on the same page:

- *all* maps mentioned/used in the Xproc spec are of type `map(*)`, meaning map with any (atomic) type as key to any type of value. For instance for maps passing parameters to p:xslt or for passing serialization parameters. But also for the map you get when requesting the document-properties.
- These maps are allowed to have *two* types of keys (all other keys are invalid):
  - Keys of string type must be valid NCnames and are interpreted as xs:QName in no-namespace. This is (for keeping things simple and the syntax concise reasons) the preferred way to represent this
  - Keys of type xs:QName which are what they are, a QName in a namespace (or no namespace)

Lets also define then that `p:document-properties()` returns a string key for all properties not in a namespace.

**Comment by xml-project** [comment]
I would agree with @eriksiegel 's  first point but have some reservation against 2 and 3.
I think we should say, which keys (name/type) WE use and leave everything else open. This is what they call [option parameter convention](https://www.w3.org/TR/xpath-functions-31/#option-parameter-conventions) in XPath 3.1. 
So we say: 

- 'content-type' is xs:string and get($map,'content-type') returns xs:string
- 'base-uri' is xs:string and get($map,'base-uri') returns xs:anyURI

Remember that steps may return other key/value pars and I do not see, why we need to restrict these in key-type or value. => p:document-properties() return a map with all key/value pairs as they are produced by the step. But: The step has to use content-type and base-uri as defined in the specs.

**Comment by eriksiegel** [comment]
@xml-project That sounds right for document-properties. But what if you want to pass parameters to an XSLT stylesheet and put (by accident or malicious design) an, lets say, entry with integer key in? Is that an error or something silently ignored or...

**Comment by eriksiegel** [comment]
Both option 1) and 2) above are ok with me. If nobody has strong opinions, let's go for 2) I would say.

**Comment by gimsieke** [comment]
Either 1 or 2, I don’t have a preference. From a pipeline author perspective, these are problems that one is unlikely to run into. If an error is raised, the error message must report the offending keys.

**Comment by xml-project** [comment]
@gimsieke I think you are right in most cases because you will create the map especially for this step. But you might run into this kind of trouble as author if you construct one map in a variable to be used in different steps.

**Comment by eriksiegel** [comment]
So do we agree on:

> Change parameters to map{*} and say that all key/values are ignored, where the processor can't make a QName of a key.

**Comment by ndw** [comment]
Discussed and consensus reached at the 12 June 2018 f2f.
