### ISSUE TITLE
Remove name attribute from p:catch, p:finally

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#294]
See [minutes, day 2](https://github.com/xproc/Workshop-2018-02/wiki/Raw-Minutes,-7-Feb#names-on-pcatchpfinally)

**Comment by xml-project** [comment]
@ndw We decided to remove @name from p:catch and p:finally because they are non genuine steps.
However: The method to access the error port in XProc 1.0 in a catch was p:pipe step="catch-name" port="error".
How do we do this in XProc 3.0? Using p:pipe port="error" would be one way but this would make "error" a primary input port on something, which is not a genuine step.
So one way or the other this non-step wrapper has some properties of a step.

**Comment by ndw** [comment]
That's why p:catch needs a name then.

**Comment by xml-project** [comment]
@ndw Ok, but what does this mean? Did I miss something?
You proposed to remove the name from p:catch - close the issue or rename it to "remove name attribute from p:finally".
 I would opt for close issue and life with the fact, that p:finally has a name attribute relevant only for debugging.

**Comment by ndw** [comment]
Sorry. I was unclear. I think you have found compelling evidence that the name attribute on `p:catch` is necessary. We must not remove it. I concur with you, for consistency, let's live with the fact that `p:finally` has an unnecessary name, rather than removing it.

I propose we close this issue as "we were wrong" :-)

**Comment by xml-project** [comment]
Attribute name will stay!
