### ISSUE TITLE
What does "XD0055" mean?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#355]
The [specs](http://spec.xproc.org/master/head/xproc/#p.inline) say:

> It is a dynamic error (err:XD0055) if the content type value specifies a character set and the encoding attribute is absent.

I am struggling with what that means in terms of processing documents. Consider:
´´´´
<p:inline document-properties="{'content-type':'text/plain; charset=UTF-8'}">Text</p:inline>
´´´´
Why do I need an encoding attribute here. And given that the only required encoding is base64, why is a base-64 decoding required here?

**Comment by ndw** [comment]
You don’t need an encoding, but you’re forbidden from including the charset. By the time the processor gets here, the text node has already been parsed and is a sequence of Unicode characters. The encoding is superfluous at best. Consider what someone might think it meant if the charset here was something other than utf8. 

If the data *is* encoded, then it can have a charset because the processor will decode the text node into a sequence of octets that *can* be interpreted according to the charset.

**Comment by xml-project** [comment]
Thanks Norm!
May be we could find a better way to say this.
