### ISSUE TITLE
Nodes as document-properties and p:document-properties-document()

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#371]
Currently document-properties are defined as `map(xs:QName, item())`, and there is the suggestion to specify them as `map(*)`. This means, that a map might contain a node.
What is supposed to happen to this node in p:document-properties-document()? The specs say:

> Each key in the properties becomes an element, each value becomes the content of that element. 

Does this mean the node becomes the child of the element?
And what do we say about maps and arrays?

**Comment by eriksiegel** [comment]
I think (and didn't we reach consensus about that) that *all* maps, including this one, are always map(*). Let's stick to that please.

There seems to be a problem with opening the link for option 1 on my computer right now, so i cant have a look at it. But if there is some standard for it, lets follow that?

I attached some text from the programmers manual to this. You can find how I understood this whole map thing in section 5.3
[xproc-book ch5.pdf](https://github.com/xproc/3.0-specification/files/1935908/xproc-book.ch5.pdf)
. Maybe that helps because it summarizes things?

**Comment by xml-project** [comment]
I do not think we had a consensus on this, what did I miss?
I some places, where we refer to XPath function which use maps I think we should follow their lines, but even this could be disputed because we might restrict the  range for key and value.

**Comment by xml-project** [comment]
Somehow editing comments went away, so I have to pose a second comment:
If, as you said, _all maps_ are `map(*)`, then we can not use the current specs of how to represent it as an XML document any more. It did not fit when it was `map(xs:QName, item())` because it does not say how maps, functions, arrays and nodes are to be represented in the XML-document.
If move to `map(*)` an xs:integer or a xs:dateTime might appear as key and they do not make up a proper element name.
Sorry that I was not able to state my point clear enough.

**Comment by eriksiegel** [comment]
After some thinking, here is my opinion on this:
One of the goals of our XProc 3 exercise is to make the language better, understandable and explainable. I think the decision to make all maps a map(*) is one that belongs absolutely in this category. I found it easy to describe in the section in the programmer's manual which is, for me personally, a good measure of how difficult things are.
But let's keep our priorities straight. Steps and functions that convert these maps to XML are important, but *not* as important as the map(*) decision originating from the goal to make the language better. So when in some edge cases these steps/functions run into trouble thats fine (as long as for the majority of cases everything is ok). I think it's acceptable and explainable that when you put in an entry of type xyz you cannot use the XML conversion and get an error.   
Nonetheless, we should define some way to convert the majority of entry types in a map(*) to XML and back. I have absolutely no preference for this. Something like `<entry type="xs:integer" key="1234">value</entry>` for keys and something nice for map and array values? If there is some standard for that, lets follow it, even if its only for the reason we can refer to it and don't have to describe it.

**Comment by xml-project** [comment]
@ndw @gimsieke 
Could we please reach a consensus on this as soon as possible, because `p:document-properties-document()` is used in a lot of tests in my test-suite (ca. 100 or so). If you have to change the format of the returned XML document because we change document-properties to `map(*)` I have to change all this tests.

**Comment by gimsieke** [comment]
It will make the life of pipeline authors harder if the result of `p:document-properties()` were `map(*)` instead of `map(xs:QName,item())`. There is some value in having the keys as element names in `p:document-properties-document()`. 
If the property values are maps or arrays, we should include the [json-to-xml()](https://www.w3.org/TR/xpath-functions-31/#json-to-xml-mapping) representation in the corresponding element (whose name is the property name) in the properties document. If the values are functions, I don’t know. Maybe make it implementation-defined whether and how to represent `item()`s other than atomic values, element/text/comment/PI nodes, maps, and arrays. 
Not sure how to represent document nodes as values in the properties document so leave it up to the implementation or say that they will be dissolved and replaced with their content node(s?).

**Comment by xml-project** [comment]
I strongly agree with @gimsieke that having keys as element names is an important point for pipeline authors. So we need a type for keys, that allows this construction or (which is the opposite point) excludes those types as key, that will not result in proper element names.
The reservation we had against `xs:QName` as type for the keys was, that we can not write
`p:document-property(., 'content-type')` but have to write `xs:QName('content-type')` over and over again in my pipeline.
Last week I was thinking about a union type for the key as `union(xs:string, xs:QName)` but I found out that this is not a viable way for Saxon based XProc processors since user-defined types are Saxon EE only.
To solve the problem with the construction of QName I would propose to have an additional function 
````
p:document-property($doc as document-node(), $key as xs:string) as item()?
````
which is the same as
````
p:document-property($doc, xs:QName($key))
````
This shifts the burden of constructing the QName to the implementation and therefor solves the xs:string vs. xs:QName problem.
For the value problem I think we should follow @gimsieke 's proposal.

**Comment by gimsieke** [comment]
I second the proposed second function that accepts a string as the second argument and then casts it to a QName (as specified in [XML Schema Part 2: Datatypes Second Edition](https://www.w3.org/TR/xmlschema-2/#QName)). 
Not in order to stifle debate but rather merely for the sake of adding some more “second”s to this comment, I suggest that we don’t waste a second waiting for a second opinion and agree to proceed as suggested.

**Comment by xml-project** [comment]
OK, I will try to write the prose and make a PR. But since I am on vacation this weekend it will probably take until Monday or Tuesday.

**Comment by cmarchand** [comment]
I do agree with the reached consensus. Keeping property names as element names is a strict necessity. Having a second function where property name is a `xs:string` simplifies the pipeline writing.

Do we allow the use of a qualified name as a string : `p:document-property($doc, 'els:myOwnProperty')`, and let the processor resolve the string as a QName according to inscope namespace mapping ?

This could be an interesting feature for writers, but is much more complex to implement...

**Comment by xml-project** [comment]
No, it was probably what you wished for but not what I proposed. ;-)) 
But looking at the specs again: The function call is an XPath expression and for processor evaluated XPath expressions all in-scope namespaces are visible, so a prefixed string could be resolved in this context.
However no in-scope namespace is visible in step evaluated XPath expression, so using a prefix string in these contexts will always result in an error.
I am pretty sure that this will be a recurring question on any help list.

**Comment by xml-project** [comment]
Yes, exactly this argument occurred to me some minutes ago and I was actually editing my previous to remove my mistake!

**Comment by gimsieke** [comment]
Resolution: Use `map(xs:QName, item()*)` consistently in the spec

**Comment by ndw** [comment]
The consensus here has been implemented. I'm closing this.
