### ISSUE TITLE
Additional attribute "content-type" on p:inline, p:document and p:load

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#385]
As I am changing the test suite for XProc 3.0 to our resolution in issue #371 , I had to write a lot of
````
document-properties="map{xs:QName('content-type'), 'text/plain'}" 
````
Since only setting the content-type property will be a very common use-case, I propose to add attribute `content-type? = {xs:string}` to the constructs that have an attribute `document-properties`(p:inline, p:document and p:load).
Semantics:
`content-type="some-text"` is a short cut for 
````
document-properties="map{xs:QName('content-type'), 'some-text'}" 
````
It is a static error if the construct has an attribute `content-type` and an attribute `document-properties`.

Please give me a thumb up if you like the idea so I know it is worth to invest time in creating a pull request.

**Comment by xml-project** [comment]
Of course you could do a workaround and declare a variable for every content-type. My proposal is just syntactic sugar, so you do not have to do it.

@gimsieke Concerning your questions:
(a) No, you can't use EQNames like in `select(Q{}content-type, 'text/plain')` because if you look at the production rules in XPath 3.1 syntax, `Q{}content-type` is not a string, but an element name which will select an element in no namespace with the name 'content-type' from the context-node of the expression. And since there is no context-node in your case, it will be an error. (If think @eriksiegel made this point after Prague after asking Michael Kay.)

(b) No, you do not need to use curly brackets in `document-properties="$text-plain"`because we decided, that the value of every option marked as map or array is interpreted as an XPath expression because the distinction between literal value `"$text-plain"` and XPath expression returning the value does not make sense here.

But looking at the specs we removed all curly brackets around map values in the syntax boxes, so they currently are not allowed to be AVTs, but we do not state the "map = XPath expression" rule anywhere. At least I have not found it either.

Your workaround corrected would be:
````
<p:variable name="text-plain" as="map(xs:QName, item()) 
  select="map{xs:QName('content-type'):'text/plain'}" />
````

My proposal is that you can skip the variable declaration and to give authors the opportunity to write
````
<p:with-input>
  <p:inline content-type="text/plain">Text document</p:inline>
</p:with-input>
````
Did I made my point clear?

**Comment by gimsieke** [comment]
Yes, your point is well understood. 
I was wondering whether the clumsiness is confined to writing test suite cases (where it is acceptable to copy&paste awful map constructors) or whether it is an actual pipeline authoring issue.
When reading binary documents, the content type may be inferred by the processor, using whatever method is available (file name extensions, content sniffing, …). So it might be useful when reading a file as text/json when there is no .json extension, reading XML as plain text or, as in your example, inlining text.
Do we specify somewhere that if no content-type is given, the processor should attempt to infer it? If so, the problem might be reduced to inlining text/json that shouldn't be read as text/plain.
I'm not sure that it is an issue that will happen in practice often. But I'm not against a content-type attribute that may be used instead of a document-properties attribute.

**Comment by gimsieke** [comment]
Then let's have it!

**Comment by ndw** [comment]
I think this is a good idea.

**Comment by ndw** [comment]
Per 11 June f2f, it's only an error if the `content-type` attribute is specified and the `document-properties` map includes a `content-type` key.

**Comment by xml-project** [comment]
Are we ok with the fact that this has to be a dynamic error, because it can only be discovered at runtime?

**Comment by ndw** [comment]
Has to be.
