### ISSUE TITLE
Remove XD0041

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#387]
Currently we have 

> XD0041: It is a dynamic error if the map contains any property name not recognized as a serialization parameter.

so an error has to be raised, if the map "serialization" on p:output has an additional/unrecognized property. This is different from XPath 3.1, where in the map parameter in "[fn:serialize()](https://www.w3.org/TR/xpath-functions-31/#func-serialize)" is treated according to the [option parameter convention](https://www.w3.org/TR/xpath-functions-31/#option-parameter-conventions). In clause 4 it says:

> It is not an error if the options map contains options with names other than those described in this specification.

Proposal: Remove XD0041 and do like XPath does.

**Comment by gimsieke** [comment]
Agreed. If a processor supports, for example, [`saxon:line-length`](https://www.saxonica.com/documentation/index.html#!extensions/output-extras/serialization-parameters), another processor that doesn’t support this serialization parameter (because the processor uses Saxon-HE or doesn’t use Saxon at all) should not raise an error if this parameter is supplied in a pipeline.

**Comment by xml-project** [comment]
Fixed with pr #390
