### ISSUE TITLE
Move @expand-text to generic attributes?

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-specification#435]
We decided to make @expand-text a more generic attribute. When I look in the spec it is mentioned in a lot of places. That's ok but cumbersome. Maybe we must make it a truly generic attribute (like @use-when), mention it as such and remove it from all the separate locations where it is now mentioned in the spec? 

Your opinions please... :-)

**Comment by xml-project** [comment]
We need to have @expand-text on any element which may have a p:inline or an implicit inline as child. That means almost anywhere, so this make me think, making it generic might be ok.
On the other hand -if we want a clear syntax- making it generic would also allow the attribute on p:document, p:documentation etc. where it absolutely makes no sense.
All in all I do not want it to be generic, but if you decide otherwise, I can life with it.

**Comment by ndw** [comment]
*shrug*

Erik observes that the current situation clutters the documentation and potentially makes XProc harder to understand. On that basis, I'm in favor of making it global. Yes, that means you can put it in places where it will have no possible effect. There's no reason an implementation can't issue warnings about that. :smile:

**Comment by eriksiegel** [comment]
@ndw I don't mind that its allowed *almost* anywhere, that's easy to explain. I just noticed that it was mentioned in so many places, it would clear up and shorten the specs if we moved it to the generic category.
Lets leave it as it is now, no problem. Close issue?

**Comment by ndw** [comment]
I don’t want to close it if we think we might want to reopen it later. Might as well sort it out once and for all now.

**Comment by eriksiegel** [comment]
Ok. Lets discuss this next call July 12

**Comment by eriksiegel** [comment]
Consensus 12/7 attribute is is generic

**Comment by ndw** [comment]
https://github.com/xproc/3.0-specification/wiki/XProc-3.0-editorial-team-minutes,-12-July-2018
