### ISSUE TITLE
Why secondary inputs unbound by default?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#447]
In the course of investigating the discrepancy between xs0003 and xs0032, I came across this text in _5.2 p:with-input_:

> If no connection is provided for a primary input port, the input will be connected to the default readable port. It is a static error (err:XS0032) if no connection is provided and the default readable port is undefined.

I’m very surprised by the restriction to *primary input port*s. I thought _all_ unconnected inputs read from the default readable port by default, both primary and non-primary ones. The prose goes all the way back to XProc 1.0 and my 1.0 implementation does indeed get it right, but the error message is totally goofy.

Wouldn’t it be less confusing if any unbound input port read from the default readable port?

It would mean that leaving out a secondary port would have a different outcome, but it doesn’t seem like a bug you’d be likely to miss. What’s more, it seems very strange to me that you can default the source port of `p:insert` but not the insertion port.

**Comment by eriksiegel** [comment]
Let me summarize how I've always understood it (as a non-implementor), this is a quote from the XProc-book-to-be:

- Input ports must always be connected to something (even if it's to "no input"), you can't
leave them hanging around. This connection can be a default connection (specified in the
step's declaration), an implicit connection (for primary ports) or an explicit connection.
- Primary output ports must also be connected to something, their output must flow
somewhere. You can of course decide to throw it away (by connecting them to a p:sink
step), but you have to do so explicitly.
- Non-primary output ports can be left dangling. All output appearing on these ports is
discarded.

**Comment by eriksiegel** [comment]
So primary input ports auto-connect to the default readable port, non-primary input ports *don't*. As far as I understand that's how it works in 1.0.

I would be against changing this because auto-connecting non-primary input ports breaks IMHO the whole intuitive way steps auto-connect through primary ports. And it doesn't really make sense: What about the insertion port on a p:insert? Its better to get an error message when you forget to connect it than silently auto-connect it.

**Comment by xml-project** [comment]
> Wouldn’t it be less confusing if any unbound input port read from the default readable port?

Quite the opposite, I think, so I definitely agree with @eriksiegel:
Primary input ports get connected to the default readable port because they deal with the documents following through the pipeline. Other input ports introduce new documents from the outside or from somewhere on the flow.

If we want an "auto-connection" for secondary input ports, I would propose to auto-connect them to p:empty, so the pipeline author does not have to do this by hand. If (by the inner logic of the step), the input port needs some documents (like on p:insert or p:xslt), the processor will complain, because the port will be declared non-sequence!

**Comment by ndw** [comment]
I surrender. Let's leave the status quo, as it is, not as I (mis)understood it! :smile:
