### ISSUE TITLE
More info on c:file and c:directory in p:directory-list?

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-specification#476]
Would it be very costly to run the equivalent of [`pf:info`](https://www.w3.org/XML/XProc/docs/fileos/#pf-info) on each file and directory item in the list? This way, users have information readily available for which they’d otherwise have to run `p:viewport` with `pf:info` on the listing. If it is too costly, maybe we can introduce a boolean attribute called `detailed` or `info` that will switch on this behavior?

**Comment by xml-project** [comment]
I think this should work. For "file://" it seems to be almost without any cost, but for other schemas it could come with some performance costs So having an attribute `detailed` (or any other name) with default value `false()` seems to be a good idea.

**Comment by ndw** [comment]
As you say, it's just about free for file:// URIs. I'm not sure it's worth having a detailed flag though, given that it's probably practically impossible in the general case. It's not clear that `p:directory-list` is going to be useful for anything more than file:// URIs anyway.

I think we should say that implementations _should_ return the `p:info` details for file:// URIs. I favor should over must because there may exist filesystems for which it isn't possible to determine some properties.

**Comment by xml-project** [comment]
I use it for webdav a lot and sometimes for xml databases where you have the notion of a "collection". I these cases I would like to control whether I get the additional information or I get the standard information in half the time. 
The flag is therefor very important from my point of view, but may be we should make it optional with default set to `true`.

**Comment by ndw** [comment]
Fair enough.
