### ISSUE TITLE
Why is attribute 'collection' an AVT?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#481]
I fail to see, why `@collection` on p:variable, p:option, p:when is an AVT. 
As far as I understand it, the attribute controls whether the binding is exposed to XPath as context item or as default collection. Right?
But the XPath expression is static, so a pipeline author can not change it during dynamic evaluation. So  the XPath expression is statically either depending on the context item or the default collection. Right?
So if I change `@collection` from true to false or vice-versa IMHO the only effect is causing an XPath error.
What did I miss?

**Comment by xml-project** [comment]
OK, I figured out one use case myself (but you have to admin its tricky):

````
<p:variable name="var" collection="{$number-of-docs &gt; 1}" 
select="if (count(collection()) = 0
   then (expression relying on the context node)
   else (expression relying on collection() )
````

But that does only work if the XPath processor (like Saxon and MorganXPath) supports lazy evaluation. But an XPath processor is not required to support lazy evaluation.

@ndw Is this the use case you had in mind, when you marked @collection as AVT?
Would it help to say in the collection case the context item is the empty sequence? This shouldn't lead to an error for no processor.

**Comment by ndw** [comment]
I don't think I had a particular use case in mind, and if it turns out to be complicated, I don't feel strongly about making it an AVT. It's even possible that making it an AVT was something that was done without consciously thinking about the consequences.

But with a few minutes thought, I'm not seeing the harm. I'm not following you about lazy evaluation. The `select` expression on a `p:variable` that refers to the context in any way (either the context item or the `collection()`) can't be evaluated until runtime anyway. At runtime, you can evaluate the `collection` attribute first and then setup the context for the expression.

In point of fact, I expect the `collection` attribute will only be set in a vanishingly small number of pipelines and that it will be set to a static constant in the overwhelming majority of cases.

**Comment by xml-project** [comment]
@ndw Thanks you: You are of course right: I just remembered that an XPath processor is allowed to evaluate the then-expression and the else-expression without knowing the result of the test-expression. But it  is of course forbidden for raise an exception before knowing the result of the test-expression. So the use-case I developed should work on any conformant XPath processor.

I do not see any harm either of @collection as an AVT. I just stumbled over it when I made the list of problematic cases for @gimsieke 's request that ALL AVT refer to the context item.
