### ISSUE TITLE
Is more clarification needed around p:declare-step/p:library/p:variable?

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-specification#513]
Sorry to open this can of worms again...

I was picking up on our conversation a while ago on the static variable usage (to describe this in the programmers reference) and read through what is now in the spec. I miss certain aspects I remember we've talked about. But maybe I misunderstood or did not follow completely. And some things need a bit more prose I think (which I'm happy to add once I understand things correctly);

1. I thought we agreed that in the prolog of a p:declare-step you could only declare and use  **static** variables. I don't see this specified. It says: _"The in-scope bindings at the beginning of a p:declare-step are limited to the lexically preceding, statically declared options and variables."_ But nothing about what exactly is allowed inside the p:declare-step's prolog.
1. If you want to use the value of an option in the prolog (e.g. to specify a default for something like another option), must this referenced option be static?
1. A variable declared at the top level of a p:library must be static. This is mentioned in 17.4.4. (about static variables and options) but probably should be mentioned in the description of p:library as well.

So more specific:
1. What kind (static or not) of _variables_ can you _declare_ in a step's prolog
1. What kind (static or not) of _variables_ can you _use_ in a step's prolog
1. What kind (static or not) of _options_ can you _use_ in a step's prolog

We can defer this to Leipzig if it causes too much discussion...

**Comment by xml-project** [comment]
> Sorry to open this can of worms again...
These day, you never know, what opens a can of worms, so no need to be sorry. ;-))

I think you right, we need some more prose (and some more errors). Let me _try_ to answer your questions (as far as I understand our consensus) and then see what happens:

1. You can only declare _static_ variables in the prolog, because any `p:variable` without a `@static` or `@static=false` would be the first element of the subpipeline. I am not sure, we say this explicit anywhere and I do not think we have an error when a static variable is declared in the subpipeline.

1. What kind of variables can you use in prolog: Only static ones. Because use has to follow declaration and declaration start subpipeline (see 1).

1. What kind of option can you use in prolog: On @select in p:option the specs say:

> It must be a statically valid expression at that point. Consequently, if it contains variable references, they can only be references to preceding options on the step.

What that means precisely is not yet decided. (See issue  #506 and #473) 

Concerning static variables and option in p:library: Yes, I think we should say more here. Currently I am not sure, static options at p:library-top level will make it. Somebody asked (found no reference, so it would be in a conversation) how to set them externally and if you can not set them, they are useless, aren't they?


@gimsieke and @ndw could you please correct my answer if necessary.

**Comment by eriksiegel** [comment]
All right, that means for the **prolog**:

1. You can only declare static variables
1. You can declare static and dynamic options
1. You can only use XPath expressions that can be evaluated statically, so they can only reference static variables and options.

So, just to check, that would mean that this is forbidden?

`<p:option name="a"/>
<p:option name="b" select="$a"/>`

About declaring static variables in the sub-pipeline: It would not make much sense but I also don't see a reason to forbid it.

**Comment by xml-project** [comment]
Your statements (1) and (2) express _my_ understanding of the current state of discussions, so yes. But may be I am wrong.

To my understand (3) is to general: In (7.1) the specs lists the expressions which have to be static: (a) XPath on static variables and options, (b) Value templates on p:input/p:output and their descendants, (c) use-when. Dynamic `p:option` are not mentioned here, so they `select`-attribute is not evaluated statically, at least to my understanding.
There is a special rule for (dynamic) [p:option](http://spec.xproc.org/master/head/xproc/#p.option): 

> It must be a statically valid expression at that point. Consequently, if it contains variable references, they can only be references to preceding options on the step.

According to this rule, your code example is allowed, as far as I understand it. What is open, is whether you are allowed to use static variables (only options are mentioned in the rule) and whether you can reference static options/variables not "on the step" but on the parent step or in the p:library.

But again: Do not rely on _my understanding_, since I am mostly wrong these days. Better wait for @ndw or @gimsieke to answer.

**Comment by eriksiegel** [comment]
All right, too many questions... I suggest to put on the agenda for Leipzig.
