### ISSUE TITLE
We don't need p:sink anymore

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#536]
In order to solve #482 we removed the rule, that the primary output port of a step has to be connected.

Since the sole purpose of p:sink was to be connected to an unused primary output port, I do not think, we need this step anymore.

Right?

**Comment by gimsieke** [comment]
I have tried to think of use cases for `p:sink`, but I have failed to do so. I thought maybe at the end of the pipeline, when you don’t want the result of the subpipeline’s last step be connected to the primary output and instead prefer to have nothing there. But if you want to have nothing on the declared pipeline’s primary output, you can connect `<p:output port="foo" primary="true"><p:empty/></p:output>` and let the last subpipeline step’s primary output drop on the floor.

**Comment by ndw** [comment]
We don't need it, but I don't think it does any harm and I don't think we should remove it.

**Comment by gimsieke** [comment]
[Conspiratorially whispering to @xml-project] I think he’s on the sink industry’s payroll.

**Comment by eriksiegel** [comment]
I agree that we don't need the sink any more. Keeping it however is probably a good idea because using it might make your pipelines better understandable. Deliberately stopping a document stream by ending it with a `p:sink` provides a clear signal IMHO. 

And it might be easier to translate V1 pipelines if there's still a `p:sink` around.

I won't oppose the decision to dump it but I think its slightly better to keep it.

**Comment by xml-project** [comment]
So: Let's keep it.
