### ISSUE TITLE
On the subject of usability

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#562]
I was just writing a little demo pipeline when I came to this:

```xml
...
<p:otherwise>
  <p:identity>
    <p:with-input>
      <p:inline>Something went wrong</p:inline>
   </p:with-input>
  </p:identity>
</p:otherwise>
```
I wonder if `p:message` as a syntactic shortcut for this form of `p:identity` would be a win.
```xml
<p:otherwise>
  <p:message>Something went wrong</p:message>
</p:otherwise>
```
Maybe `p:message` isn't the ideal name.

**Comment by gimsieke** [comment]
There’s already a proposal for a step called `p:message` (https://github.com/xproc/steps/issues/2).
Also, there’s the proposed `p:message` option (#29).
What your `p:message` is not emitting a message (to stderr or stdout) at all, but it returns a text document. I don’t think we need an extra element for this. 

Can we probably adopt a broader definition of implicit inlines? That is:
When you write `<p:identity>Something went wrong</p:identity>`, not only will the missing `p:inline ` be “inserted” by the processor but also the `p:with-input` for the primary input.

**Comment by gimsieke** [comment]
Still, I’d like to propose an extended notion of implicit inlines instead of a shortcut for `p:identity` with implicit primary port binding. Like:
```xml
<p:add-attribute attribute-value="{count(collection())}" collection="true" attribute-name="bar">
  <foo/>
</p:add-attribute>
⇒ <foo bar="3"/>
 
<p:wrap wrapper="foo"><bar/></p:wrap>
⇒ <foo><bar/></foo>

<p:wrap-sequence wrapper="foo"><bar/><baz/></p:wrap>
⇒ <foo><bar/><baz/></foo>
```
Extended notion means: You can omit the `p:with-input` primary port binding in addition to the `p:inline`.
We can specify that all non-XProc, non-withespace nodes will be implicitly fed into the primary input, with the usual error checking (if sequence is not true, only a single element is allowed; text nodes are only allowed if the step accepts `text/*`; etc.).

**Comment by ndw** [comment]
What do you propose to say about steps that have more than one input? Is this allowed?
```xml
<p:insert position="first-child">
<doc/>
</p:insert>
```
What does it mean?

**Comment by gimsieke** [comment]
```xml
<p:insert position="first-child">
  <doc/><!-- primary input-->
  <p:with-input port="insertion"><foo/></p:with-input>
</p:insert>
⇒ <doc><foo/></doc>
```
(Comments and PIs probably need to be ignored, like whitespace nodes at the top of an implicit inline.)

**Comment by ndw** [comment]
That didn't really answer my question. I assume that your answer to my question is that `<doc/>` is the primary input and the secondary input comes from the default-readable-port.

**Comment by gimsieke** [comment]
As I said above: The non-XProc (namespace) children (of p:insert, in this case) will be treated as the primary input (wrapped in document nodes if necessary). The non-primary outputs need at least a `p:with-input` around them before they also can be given as implicit inlines. The DRP in the example above will not be considered because both inputs of `p:insert` have been explicitly connected (to inlined content).

**Comment by gimsieke** [comment]
In your example, the secondary input won’t be connected, that means, an empty sequence appears on the insertion input, which effectively leaves the input as it is. If secondary inputs were not specified as sequence, an error would be raised if there was no connection given (they won’t read the DRP, will they?).

**Comment by eriksiegel** [comment]
We close it for now.
