### ISSUE TITLE
Is the select attribute on p:input really worth the trouble?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#570]
In XProc 1.0, we used the `p:input` element for both declaration and use of inputs. We obviously needed a `select` attribute on the uses, so the least surprising thing to do seemed to be to give it a meaning on the declarations as well.

But now when I read:

>    The select expression applies only if the default connection is used. If an explicit connection is provided by the caller, then the default select expression is ignored.

I think that sounds like potentially confusing behavior for a very narrow use case.

We have `p:with-input` today. Is it worth considering a simplification and removing `select` from `p:input`?

**Comment by xml-project** [comment]
My first thought would be to keep it like it is, because I often use
````
<p:input port="source" select="/doc/element">
   <p:document href="uri" />
</p:input>
````
to provide a default document from a larger document used on other steps. Does this make sense?

My second argument would be that it becomes difficult for authors to port their XProc 1.0 pipelines to version 3.0 in the selecting from a document case.

**Comment by ndw** [comment]
Ok, I guess it is then :-)
