### ISSUE TITLE
Names on p:when violate normal scoping rules

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#645]
I don't (think I) object to putting names on `p:when` elements, but note that this does introduce a need to say something about "non step wrappers" or something equivalent.

Normal scoping rules don't apply since, for example, `p:otherwise` must not be able to read from the preceding sibling `p:when` "steps" but now that they have `name` attributes, it would be possible to write `p:pipe` elements that did so.

**Comment by xml-project** [comment]
Sorry to cause problems, but where is the difference between non-step wrappers p:when/p:otherwise on one hand and p:catch/p:finally on the other hand. To my understanding with respect to scoping, both are the same. So why can p:catch/p:finally have names (and cause no trouble) and p:when/p:otherwise not.

**Comment by ndw** [comment]
Sorry. I wasn’t trying to suggest it was different. I was just reminded that it’s an issue we have to tackle.

Not having names on p:when may have been an effort to avoid a problem, but I can see how it would make some things more difficult.

**Comment by xml-project** [comment]
Another though: In XProc 1.0 p:when/p:otherwise did not have a name, but p:catch had. The reason for this seems to be the fact that input port "error" on p:catch is not primary. To access this port, one has to write `p:pipe step="catch-name" port="error"`. Following this logic, p:finally in XProc 3.0 has to have a name too.
What if we make port `error` a *primary input port* for p:catch/p:finally? There would be an auto-connection to the primary input port of the respective subpipeline. No need to pipe the port anymore and therefor no need for p:catch/p:finally to have a name.
Con: This change would prevent XProc 1.0 pipelines using the pipe from running in XProc 3.0.
Did I manage to expose my point?

**Comment by ndw** [comment]
Fixed in #650.
