### ISSUE TITLE
Evaluation in p:choose

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#647]
> The p:choose considers each subpipeline in turn and selects the first (and only the first) subpipeline for which the guard expression evaluates to true in its context. If there are no subpipelines for which the expression evaluates to true, the default subpipeline, if it was specified, is selected.
After a subpipeline is selected, it is evaluated as if only it had been present.

I think some addition is necessary here for the attribute "test" on p:when. Suppose there is an XPath-error in a when-expression which is located after the first when-expression that evaluates to true. Is a processor required to raise an error (which can be caught) or not?

**Comment by eriksiegel** [comment]
I would say no (for dynamic errors).

**Comment by xml-project** [comment]
Everything is fine with me: What would be the rule, authors can rely on?

**Comment by ndw** [comment]
"The processor is required to evaluate the `test` expressions on `p:when` elements in document order. It must not process any `test` expressions on `p:when` elements that follow the first such expression that returns true."

Or words to that effect. The semantic must be that it stops because surely one of the motivations for a `p:choose` in the first place is to avoid a condition that would raise an error!

**Comment by xml-project** [comment]
+1
