### ISSUE TITLE
Default settings for serialisation parameters

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#711]
Currently we [say](http://spec.xproc.org/master/head/xproc/#serialization):

> The default value of any serialization parameters not specified on a particular output is implementation-defined.

Playing a little around with this I would propose, that the processor is required to set default of 'method' according to the document type, so:

- XML document -> method = xml
- JSON document -> method = json
- Text document -> method = text
- Other documents -> Implementation defined.

Does this make sense to anyone?

**Comment by eriksiegel** [comment]
Yes it does, quite a lot of sense actually. So +1

**Comment by gimsieke** [comment]
We can go further an stipulate a default of 'UTF-8' for `encoding` for the `xml` and `xhtml` methods, and a default value of `1.0` for `version` with the `xml` method.

If the content type is `application/xhtml+xml`, the default method is `xhtml`. If the content type is `text/html`, the default method is `html`. This is the reversal of the [`media-type` value setting according to the chosen `method`](http://spec.xproc.org/master/head/xproc/#xproc-xml-serialization.4.9.2.1.1). Since in 3.0 each document has a content type, I think it makes sense to specify the default methods for each type by applying this mapping in the reverse direction.

There’s also this sentence for `omit-xml-declaration`: 

> The omit-xml-declaration must be supported. If the value is not specified or has the value no, an XML declaration must be produced.

In the 1.0 spec, when there was the `omit-xml-declaration` attribute on a standard step, it would always default to `'true'`. Therefore a processor didn’t have a choice but to omit the XML declaration if the option was missing. I think now the situation is different if the sentence above holds: There is no default any more for the `omit-xml-declaration` map entry, therefore a 3.0 processor must now produce an XML declaration if `omit-xml-declaration` is not specified.

Another random observation: In the steps spec, we still occasionally refer to XSLT 2.0 and XQuery 1.0 serialization (for ex. in [`p:escape-markup`](http://spec.xproc.org/master/head/steps/#c.escape-markup). It should probably link to [XSLT and XQuery Serialization 3.1](https://www.w3.org/TR/xslt-xquery-serialization-3/) or to [§ 16.3.1](http://spec.xproc.org/master/head/xproc/#serialization) where we link to the current 3.1 serialization spec.

**Comment by xml-project** [comment]
@gimsieke could you please move your comment to a new issue because it deals with a related, but different point.
I think your suggestion is more controversial, so I could not fix the easy point I raised with a simple PR. Of course you are right, I missed method="html" in my list.

**Comment by gimsieke** [comment]
Which part of it? The reverse application of the [`method`→`media-type` mapping table](http://spec.xproc.org/master/head/xproc/#xproc-xml-serialization.4.9.2.1.1) (and also including `json` in the table, I didn’t mention that above) was intended as an immediate amendment to your proposal, so we should discuss it here.
For the two other issues raised in the comment I will create different issues.

**Comment by xml-project** [comment]
@gimsieke 

> For the two other issues raised in the comment I will create different issues.

Thanks.

> The reverse application of the method→media-type mapping table (and also including json in the table, I didn’t mention that above) was intended as an immediate amendment to your proposal, so we should discuss it here.

Of course: I think your proposal is right: We must not reply on the document type to set the default output method, but on the value of property "content-type". I missed that in my original proposal.

**Comment by gimsieke** [comment]
#712, #713
