### ISSUE TITLE
What do we say about serialization of XDM documents?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#722]
Suppose a document in XProc is a valid instance of XDM document, but not a well-formed XML document, like:
````
text
text
<doc />
<doc />
````
What is supposed to happen, if it appears on p:store or p:http-request, where it should be serialized using method 'xml'? An error or pass?

And what if it is a pipeline result to be serialized by the processor?

**Comment by gimsieke** [comment]
I think we already discussed that we will handle the results more XQuery-like, so there is no requirement that a well-formed XML document be produced by serialization.
So it should be normalized into a document node that contains a (single) text node and two `doc` elements. 
(As I understood [sequence normalization](https://www.w3.org/TR/xslt-xquery-serialization-3/#sequence-normalization), if `text` are instances of `xs:string` rather than text nodes, and if `item-separator` is not specified, there will also be a space inserted between the items.)

**Comment by gimsieke** [comment]
In [16.3.1 Serialization parameters](http://spec.xproc.org/master/head/xproc/#serialization), we say:

> These parameters control XML serialization as defined by [[Serialization](https://www.w3.org/TR/xslt-xquery-serialization-30/)].

(This link to Serialization 3.0 should be updated to [Serialization 3.1](https://www.w3.org/XML/Group/qtspecs/specifications/xslt-xquery-serialization-31/html/) btw.)

The serialization spec defines XML serialization for well-formed documents and for well-formed external general parsed entities. The production rule for the latter is given [here](https://www.w3.org/TR/REC-xml/#wf-entities):

```
[78] extParsedEnt ::= TextDecl? content
[43] content ::= CharData? ((element | Reference | CDSect | PI | Comment) CharData?)*
```

There is no requirement to normalize to (and later serialize as) well-formed _documents_ in the serialization spec IMHO.

The bracket part: If `text` in your example are text nodes, they should be merged according to _S<sub>6</sub>_ in [sequence normalization](https://www.w3.org/XML/Group/qtspecs/specifications/xslt-xquery-serialization-31/html/#serdm). If, however, they were strings and if no `item-separator` is given, the strings need to be joined by a space according to _S<sub>3</sub>_.

**Comment by xml-project** [comment]
+1
