### ISSUE TITLE
How to identify a text document only on a port

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-specification#747]
In updating the text steps I stumbled on this problem:

What would be an appropriate value for `@content-types` on a port declaration that specifies that *only* text documents can flow in or out.

If I specify `content-types="text/*"` this also includes `text/xml` which is not a text document. But `content-types="text/plain"` seems too restrictive to me...  Anybody any advice?

**Comment by ndw** [comment]
Using `text/xml` is a bad idea. I thought it was actually deprecated, but it turns out that by the time [RFC 7303](https://tools.ietf.org/html/rfc7303) came out that wasn't actually necessary (because of changes in the underlying text media type specifications).

I don't think we can do better than `text/*` for media types on ports, unfortunately.

We could say that `text/*` is interpreted by XProc as meaning any text media type *except* `text/xml`. We already note that distinction somewhere in the spec. But I don't know if that's worth it.

**Comment by Conal-Tuohy** [comment]
`text/xml` is a sad legacy, but unfortunately it's pretty standard and is even the default media type for XSLT output I believe.

**Comment by eriksiegel** [comment]
All right, I'll stick to `text/*`

**Comment by Conal-Tuohy** [comment]
I haven't been following the spec development closely enough, so this may be a dumb idea, but could it help to add another kind of "document type" (other than the IANA media type) analogously to the XSLT/XQuery serialisation `method`parameter? i.e. with values "text", "xml", "json", etc? If this option were explicitly part of the step declaration as well as in the metadata associated with each document it could resolve the ambiguity here (you could declare the port to have `document-type="text"` and it would not even need a `content-type` necessarily) and also usefully provide default values to `p:store` steps.
