### ISSUE TITLE
Non-XML serialization

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#788]
Currently we [say](http://spec.xproc.org/master/head/xproc/#xproc-non-xml-serialization):

> The names and values of non-XML serialization parameters are implementation-defined.

Doesn't it make sense to say, for JSON and text we align with
[XSLT and XQuery Serialization 3.1](https://www.w3.org/TR/xslt-xquery-serialization-31/)?

Did I miss something?

**Comment by gimsieke** [comment]
Yes, we should probably say so.

**Comment by ndw** [comment]
👍

**Comment by xml-project** [comment]
It does!

**Comment by xml-project** [comment]
Could somebody give me a hint what to do here? I don't think it make sense to copy the sections on XHTML, HTML, TEXT and JSON from "XSLT and XQuery Serialization 3.1" here.

**Comment by gimsieke** [comment]
Most of the content of the present section [16.3.1.1 XML serialization](http://spec.xproc.org/master/head/xproc/#xproc-xml-serialization) (in particular, the list of serialization parameters) seems to be copied verbatim from the XProc 1.0 spec, with some amendments, for ex. wrt the `json` method. 

Maybe we can drop most or all of this subsection because we already refer to Serialization 3.1?

Historically, the heading was changed from [“serialization options”](https://www.w3.org/TR/xproc/#serialization-options) to “XML serialization options” while the content partly still applies to text, json (new), html, and xhtml.

For example, “**escape-uri-attributes**: The value of this option must be a boolean. It is ignored unless the specified method is `xhtml` or `html`.” does not need to be mentioned at all in a section about serialization parameters for the `xml` method. The global reference to Serialization 3.1 already covers that `escape-uri-attributes` [does not apply to the `xml` method](https://www.w3.org/TR/xslt-xquery-serialization-31/#XML_ESCAPE-URI-ATTRIBUTES).

We should discuss tomorrow what to do. My gut feeling is that we should dissolve the two subsections 16.3.1.1 and 16.3.1.2. The content of 16.3.1.1 before “In order to be consistent with the rest of this specification, …” may probably be omitted. 

In the following paragraph (“The method option controls the serialization method used by this component …”), why do we (and why did the 1.0 spec) use the word “component”? 

IMHO, 16.3.1.2 is anticipated by “Implementations may support other method values but their results are implementation-defined.” and may be dropped entirely.

**Comment by ndw** [comment]
Consensus: our serialization parameters section should say that the names of the parameters come from the map and the meaning of the parameters and the semantics of serialization come from the XPath/XQuery/XSLT serialization spec.

**Comment by ndw** [comment]
Note: we need to preserve the sentence about true/false vs. 1/0/yes/no
