### ISSUE TITLE
text/xml no longer XML?

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-specification#790]
Didn't we decide somewhere that media type `text/xml` is no longer considered XML but text? Can't find it and the spec still says `text/xml` is XML. 

Does anybody have a better memory than me?

**Comment by gimsieke** [comment]
I don’t think that we took this decision. I don’t remember that there was any controversy about treating `text/xml` as XML.

**Comment by eriksiegel** [comment]
I remember we discussed this because I was specifying the text steps and it was impossible to specify `@content-types` in such a way that it really only accepts text. Specifying `content-type="text/*"` would include `text/xml` as well...

**Comment by gimsieke** [comment]
I don’t think that `text/*` includes `text/xml` but maybe we should state this more explicitly. 

In the definition list after [this anchor](http://spec.xproc.org/master/head/xproc/#err.inline.D0016), there is:

> Here are some examples of content types for matching:
> …
>    `text/*`, any kind of text document.

And “[text document](http://spec.xproc.org/master/head/xproc/#dt-text-media-type)” explicitly excludes `text/xml` and `text/html`.

So the `*` wildcard apparently does not work exactly as a replacement for “any characters”. This is also seen in the other example,

> `*/*+xml`, any XML content type.

So this does not literally (in a conventional wildcard sense) match, for example, `application/xml`, but it is still supposed to match, in a content-type sense, any XML media type.

I think we should explicitly define the wildcards for common media types, instead of listing them as mere examples.

**Comment by Conal-Tuohy** [comment]
Another option would be to define an additiona document property to record the document type, and not be forced to rely on the IANA media types. e.g. there could be a `type` document property with values from `text`, `json`, `xml`, `binary` (or whatever the types are).

**Comment by ndw** [comment]
Two thoughts at the 4 April editorial call:

1. Add a notion of negating mime types, "text/* -text/xml"
2. Add a notion of shortcuts, a bare word without a "/" is a shortcut for a longer definition.

So, "text" could be a shortcut for "text/* -text/xml -text/html" for example.

**Comment by ndw** [comment]
Per 18 Apr editorial call, the two comments above are the accepted proposal.

**Comment by Conal-Tuohy** [comment]
Can I assume the media type you meant in your comment above, @ndw, was `application/xhtml+xml`?

**Comment by ndw** [comment]
Yes, I meant "application/xhtml+xml".
