### ISSUE TITLE
Further clarification on XDM step results might be necessary

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#822]
In section "[Creating documents from XDM step results](http://spec.xproc.org/master/head/xproc/#documents.6)" we say:

> If the item is a map, array or any atomic value, a JSON document is created and content-type application/json is used.

I think for atomic values  it is vague what we mean by 'JSON document' : Do we convert the atomic values as stated in for[ JSON serialization](https://www.w3.org/TR/xslt-xquery-serialization-31/#json-output) or do we take the actual XDM value.

To be more concrete: Suppose an p:xslt/p:xquery returns an instance of xs:date. If we use the JSON rules in XProc an JSON document would appear containing a string representation of the xs:date. Or will the JSON document actually contain an xs:date (which is not a JSON type)?

**Comment by Conal-Tuohy** [comment]
I agree some more clarity would be good, because there is the potential for people to be confused by the rather loose use of the term "JSON document" there. 

For the record my understanding of the consensus is that these so-called "JSON documents" may have data types and structures which cannot be represented in JSON documents in the strict sense. So "JSON document" is merely a label for such a data structure, which, if it _were_ to be serialized as JSON, might end up looking quite different. 

For instance, the `www-form-urldecode` step is supposed to produce a "JSON document" which is a map of strings to sequences of strings (sequences because there may be multiple form parameters with the same name). But NB if that map were actually serialized as JSON, any such sequences with length > 1 would cause a serialization error. 

Maybe it would be better to name these documents something other than "JSON"? More accurately they are general XDM sequences, but that's a mouthful.

**Comment by ndw** [comment]
By "JSON documents" we mean XDM maps and arrays and atomics and we need to say that clearly somewhere.

**Comment by Conal-Tuohy** [comment]
I think it's would help to reinforce the distinction between these "JSON Documents" in XProc's data model and the JSON data model itself, by explicitly mentioning that XProc "JSON documents" can include XDM instances which contain sequences with cardinality > 1 (in particular, the proposed `p:www-form-urldecode` step is able to produce such documents), and that therefore it's [not guaranteed that an XProc "JSON document" can actually be serialized using the "JSON" serialization method](https://www.w3.org/TR/xslt-xquery-serialization-31/#ERRSERE0023).

**Comment by eriksiegel** [comment]
Working on the text for this one. Would like to add a clear example of something that cannot be serialized.

Can anyone give me one or more examples of a map, array of atomic value that cannot be serialized using the json method?

E.g. can a map that has sequences of strings as one of its values not be serialized?

**Comment by martin-honnen** [comment]
@eriksiegel, any single sequence of more than one item can not be serialized with the `json` ouput method from the 3.1 serialization spec so trying to serialize e.g. `('a', 'b', 'c')` alone or within a  `map { 'key' : ('a', 'b', 'c') }` will fail using that output method.

**Comment by xml-project** [comment]
If we use method "json" to serialise an array or a map, I think the error conditions in [XSLT serialization](https://www.w3.org/TR/xslt-xquery-serialization-31/#json-output) must apply.

As an example of a map, that (in my opinion) has to raise an error, is a map, where the string value of two keys are equal (also they are not equal of equal types). E.g.:

<p:variable name="var" select="map{'123' : value1, xs:integer(123): value2}" />

**Comment by Conal-Tuohy** [comment]
I think the map `map{'123' : value1, xs:integer(123): value2}` should raise an error when serialized _unless_ the appropriate serialization option (`allow-duplicate-names`) is set: https://www.w3.org/TR/xslt-xquery-serialization-31/#ERRSERE0022 -- It's a good example to include.

**Comment by eriksiegel** [comment]
All right, thanks!

**Comment by eriksiegel** [comment]
Closed with #862
