### ISSUE TITLE
Proposal: the match attribute on p:viewport should not be an AVT

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#830]
The viewport step integrates into pipeline construction fairly deeply. I'd like to make the `match` attribute static in XProc 3.0. I'm not saying it'd be impossible to make `match` dynamic, but I think it's potentially a lot more complicated to implement and I don't believe anyone's ever asked for it. We just made as many things as we could AVTs.

I also think that if it's allowed to be dynamic, users could reasonably expect to use `p:with-option` to set it, and I really don't want to go there.

**Comment by eriksiegel** [comment]
I concur

**Comment by gimsieke** [comment]
I always considered it a Calabash bug that I couldn't use variables in the match attribute of p:viewport. Because according to the 1.0 spec, you can. And in Morgana, you can, too. So if you want to rule this out in the spec, I'm vehemently against it.

**Comment by gimsieke** [comment]
Maybe no one asked for it, but the fact that I couldn't use a match expression with a variable in Calabash was the reason I didn't write an article about XProc 2 years ago. On my way to XML London, I created [this example pipeline](https://subversion.le-tex.de/common/presentations/2017-06-11_xmllondon_xproc/samples/xpl/extract-xml-from-zip.xpl). What was intended as a showcase for a straightforward pipeline (extract files from a zip based on a regex that matches their names), proved to be inexplicably difficult. I had to use the match attribute of p:add-attribute in order to attach an extract="yes" option to the archive listing because I couldn't access the regex variable in the match attribute of p:viewport.
Achim later confirmed my assumption that match on p:viewport should be processor-evaluated and therefore be able to compute the expression dynamically.
The fact that I couldn't make this simple example self-explanatory in Calabash was the main reason I didn't complete the xml.com article back then.

**Comment by ndw** [comment]
I don't know where you or Achim got the impression that it should have been possible to set this value dynamically in 1.0 (there are no AVTs and you can't use `p:with-option` in compound steps).

However, I take your response as a "hard no" to my proposal :-)

Simple matter of implementation, I guess.

**Comment by ndw** [comment]
See https://github.com/xproc/3.0-test-suite/issues/195
