### ISSUE TITLE
Nasty consequence of manipulating base uris

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#892]
After implementing our new ruling yesterday evening, the following problem of allowing to manipulate document base URIs came up:

Until yesterday we had either document with a proper base URI (as a consequence of p:inline, p:load, p:xslt etc) and documents without a base URI, e.g. the result from p:count or p:compare.

Now since we allow pipeline authors to overwrite proper base URI with arbitrary string in the `document-properties` map, an author might attempt to remove document's base URI or overwrite the proper value with a value which is not a proper URI.

Since neither Saxon nor XOM accept an invalid URI as value for the document's base URI, and a number of steps rely on a valid URI to resolve relative URIs, I propose to have a new dynamic error which is raised, when on `p:inline`, `p:load` and `p:set-property` whenever a 'base-uri' key is present but not associated with a valid URI.

**Comment by gimsieke** [comment]
You can’t completely prevent users from shooting themselves into their feet. If someone supplies a malformed URI for `p:load` or `p:store`, they will get a dynamic XProc error or even a Java exception such as “URI is not hierarchical”.

I agree to some extent, though. But as I said on other occasions, we shouldn’t enforce strict RFC 3986 compliance. Unescaped UTF-8 characters, `file:/C:/` instead of `file:///C:/`, etc., often resolve on the given OS platform. These URIs should only raise an error if they don’t resolve to files, not if they don’t strictly comply with RFC 3986.


So I 

Currently, if you use a malformed URI, you will get a Java exception, for ex. .

**Comment by xml-project** [comment]
>But as I said on other occasions, we shouldn’t enforce strict RFC 3986 compliance. Unescaped UTF-8 characters, file:/C:/ instead of file:///C:/, etc., often resolve on the given OS platform. These URIs should only raise an error if they don’t resolve to files, not if they don’t strictly comply with RFC 3986.

Sorry, but this is not an option here because we are not talking about resolving files, but setting the base uri property per [XML base](https://www.w3.org/TR/xmlbase/). And here a proper URI is required. If you look at the APIs there is no way to supply your examples as base URI for Saxon or XOM. Both require instances of java.net.uri. 

The only alternative I see currently is to revert everything I have done yesterday and forbid manipulation of the base URI property.

**Comment by gimsieke** [comment]
I created a document containing an U+2192 UTF-8 char
```xml
<doc xml:base="file:/C:/test→UTF-8.xml"/>
```
and transformed it using Saxon 9.8.0.15
```xml
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0">
  <xsl:template match="/">
    <xsl:message select="base-uri(*)"/>
    <xsl:sequence select="."/>
  </xsl:template>
</xsl:stylesheet>
```
This was the output:
```xml
file:/C:/test→UTF-8.xml
<?xml version="1.0" encoding="UTF-8"?><doc xml:base="file:/C:/test→UTF-8.xml"/>
```
So Saxon didn’t complain about the non-compliant base URI.

I wouldn’t _define_ what is a valid URI by compliance with RFC 3986 or whether it can be represented by `java.net.uri`. Can we maybe say that an XProc processor raises a dynamic error when it encounters a base URI that it cannot represent, for whatever reason? Then it can run a purported URI string by, for example, `java.net.uri.URI()` and raise an error if it fails.

**Comment by gimsieke** [comment]
I acknowledge that interoperability would be better served if there were a deterministic procedure or a regex to validate a given URI. But since what is accepted as a URI may heavily depend on the environment (OS, encoding, host language, …), some strictly non-compliant “URIs” may still be acceptable. And where they are acceptable, people are using these non-compliant URIs all the time. We’d have to change our habits (and a lot of Makefiles) if we needed to URL-escape umlauts in file names or use `file:///` instead of `file:/` or `/` all the time.

**Comment by xml-project** [comment]
I still think, you miss the point. But any way: XOM is a strict model, so I am out on this.

**Comment by gimsieke** [comment]
Even if I miss the point: Can we still agree to raise a dynamic error if a base URI cannot be represented (for whatever reason)?

**Comment by xml-project** [comment]
I think we can close this. We should probably make a note somewhere, that the interpretation of the term "base URI property of a document" is implementation defined and then let each processor deal with what it can handle or not. 
I think it is clear, that a processor is not allowed to raise an error for a valid base URI according to RFC 3986.

**Comment by xml-project** [comment]
For resolution see: https://github.com/xproc/3.0-specification/issues/889#issuecomment-548820376
