### ISSUE TITLE
A little more explanation is needed for p:document-properties-document()

### ISSUE THREAD

**Issue by xatapult** [xproc/3.0-specification#910]
This follows changes made for #884: I was struggling to describe the output of `p:document-properties-document()`. I think it needs to be explained to be a little bit better. And for maps the current rules seem to overlook the case when the map (a map that is a *value* of a document property) has none QName keys. Happy to change any text (this week!) once I understand things.

**Arrays:**
Assume we have an array in the document properties named `EXAMPLE`, containing the values `[1, 'hi']`. I assume this will result in with _two_ entries inside `<c:document-properties>`:

```xml
<EXAMPLE array="true" xsi:type="xs:integer">1</EXAMPLE>
<EXAMPLE array="true" xsi:type="xs:string">hi</EXAMPLE>
```

**Maps:**
Assume we have in the document properties a `map(*)` named `MAPPIE` with the value `map{ a:1, 1:'booh'}`. The current rule says "serialized according to this rules". But that would, if I understand things correctly, result in non well-formed XML:

```xml
<MAPPIE map="true>
  <a xsi:type="xs:integer">1</a>
  <1 xsi:type="xs:string">booh</1>
</MAPPIE>
```

Any thoughts, especially @xml-project who brought up #884?

**Comment by xatapult** [comment]
A generic solution for the map problem above would be (although the result *is* a bit verbose):

```xml
<MAPPIE map="true">
  <c:entry>
    <c:key xsi:type="xs:string">a</c:key>
    <c:value xsi:type="xs:integer">1</c:value>
  </c:entry>
  <c:entry>
    <c:key xsi:type="xs:integer">1</c:key>
    <c:value xsi:type="xs:string">booh</c:value>
  </c:entry>
</MAPPIE>
```

All map entries would need to follow this rule, but what to do with nested maps?

**Comment by xatapult** [comment]
After some thinking and trials-and-error I propose the following:

* If you *really* need very low level access to map values in the document-properties (like getting precise key types) you can use `p:document-properties()` to retrieve the map and do the inspection yourself.
* Otherwise I would suggest to serialize the *full* document-properties map as if it was a JSON map that was passed through `<p:cast-content type content-type="XML">`. 
* This means that  the function probably needs an (optional) second parameter for the conversion `parameters`, like the `parameters` option of `p:cast-content-type`
* This implicates the rules we already have defined for `p:document-properties-document` are no longer valid and are replaced by this.

I think this is a clean solution, re-using definitions we've already made. Opinions please?

**Comment by xatapult** [comment]
Ehh, thinking just a bit more:

Maybe we could even do away with `p:document-properties-document()`, because you can always call `p:document-properties()` and run the results through an XML serialization function yourself. 

Simplify, simplify ... 😄

**Comment by gimsieke** [comment]
We have already been contemplating ([[1](https://github.com/xproc/3.0-steps/issues/16#issuecomment-500784595)], ([[2](https://github.com/xproc/3.0-steps/issues/30#issuecomment-447047003)], maybe in other issues, too) introducing a standardized param for `p:cast-content-type()` to convert from parameter maps and document property maps (as JSON documents) to `c:param-set`. 

```xml
<p:identity select="p:document-properties(.)"/>
```
Result: A map, that means, a JSON document according to [the sentence before this](https://spec.xproc.org/master/head/xproc/#err.inline.D0016.19).
```xml
<p:cast-content-type parameters="map{'c:vocab': 'document-properties'}"/>
```
Result: A `c:document-properties` document.

or

```xml
<p:identity select="p:document-properties(.)"/>
<p:cast-content-type parameters="map{'c:vocab': 'param-set'}"/>
```
Result: A `c:param-set` document.

Casting these special XML documents to JSON should produce the original maps (instead of throwing an error because it is not the `fn:map` markup).

Then we can do away with `p:document-properties-document()` IMHO.

And I wouldn’t consider this a new feature; https://github.com/xproc/3.0-steps/issues/16 where it was suggested is still open.

----

Regarding the issue “document property values are maps whose keys are not QNames”: 

Maybe we should say that the default `fn:json-to-xml()` mapping must be applied to all values that are maps (and arrays, probably).

The same for `c:param` values that are maps:

```xml
<c:param-set>
  <c:param name="foo" value="bar" xsi:type="xs:string"/>
  <c:param name="mappy" xsi:type="map(xs:string,xs:string)">
    <map xmlns="http://www.w3.org/2005/xpath-functions">
      <string key="foo">bar</string>
    </map>
  </c:param>
</c:param-set>
```
```

**Comment by xatapult** [comment]
Yes, I think `p:document-properties-document()`  makes no longer any sense. It might be there for convenience but causes too many headaches. **I propose to drop it.**

If we're not in agreement about this, maybe we can have a quick online meeting next Thursday?

**Comment by gimsieke** [comment]
I will only agree to drop it if we agree on a parameter for `p:cast-content-type` with two spec-defined values, one for creating `c:param-set` from a map, and the other one for creating `c:document-properties` from a map. Thursday 16:00 UTC (17:00 CET) is ok for a call.

**Comment by xatapult** [comment]
> I will only agree to drop it if we agree on a parameter for p:cast-content-type with two spec-defined values, one for creating c:param-set from a map, and the other one for creating c:document-properties from a map. 

Ehh, how is this related? I don't mind these parameters for `p:cast-content-type` but I don't see their relation with dropping `p:document-properties-document()`.

**Comment by gimsieke** [comment]
What I wrote in https://github.com/xproc/3.0-specification/issues/910#issuecomment-552973569

If there is no `p:document-properties-document()` any more and if I don’t want to write my own XSLT to transform the `fn:json-to-xml()`-like output that I get by applying `p:cast-content-type` to the map that `p:document-properties()` returns, then we need a parameter for `p:cast-content-type` that tells it to create a `c:document-properties` document from a map (JSON document) instead of an `fn:map` document.

**Comment by xatapult** [comment]
All right. Unless somebody objects (@xml-project agreed in a separate mail; @ndw?) I will remove this function.

Let's open a new issue for the enhancement request of @gimsieke for `p:cast-content-type`.
