### ISSUE TITLE
describe the proposed p:run compound step for dynamic evaluation

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-specification#97]
@ndw proposed a new compound step `p:run` that is intended to run arbitrary pipelines. 

In contrast to any other compound step, it need not have a subpipeline body. 

It has a special port, named 'pipeline' by default, where the pipeline to be evaluated is supplied. (Open question: Should a pipeline author be able to override this special input port name?

If it has a subpipeline body, this will serve as a fallback pipeline if none is supplied on the special port. (To be discussed; this was not part of Norm’s initial proposal.)

Input/output port mismatches between a `p:run` instance and the supplied pipeline should be resolved as follows:

- If the supplied pipeline provides additional output ports, they will be ignored.
- If the `p:run` instance binds one of its output ports to a port that the provided pipeline does not provide, the `p:run` output port will exist, but zero documents will appear on that port.
- If the supplied pipeline creates output on a primary output port while the `p:run` step does not declare a primary output port, a dynamic error will be flagged. (To be discussed: If the `p:run` instance declares exactly one output port that is non-primary and that is not connected to another port of the evaluated pipeline, should this port be connected to the pipeline’s primary output? Should be in line with what the core specs says about implicit connections.)
- If the supplied pipeline requires non-empty input port bindings that the `p:run` instance does not provide, a dynamic error will be raised from a step in the supplied pipeline that expects non-zero input on this port. No static error will be raised though.
- If the `p:run` instance attempts to connect to an input port that the supplied pipeline does not provide, the input will not be provided to the pipeline, but a dynamic warning will be issued.
 
Did I omit cases?

**Comment by ndw** [comment]
I think there has to be an option to override the 'pipeline' port name because if there isn't you can't evaluate a pipeline that has an input port named 'pipeline'.

**Comment by ndw** [comment]
I'm a little uncertain about the viability of having a fallback subpipeline. Those steps would have to have bindings and they'd be lexically in the subpipeline in a way that the dynamic pipeline can't be. I'm not opposed if it all makes sense in the end, I'm just not confident it's going to.

**Comment by gimsieke** [comment]
Ok, I’m retracting the embedded default pipeline proposal

**Comment by ndw** [comment]
# p:run

The `p:run` step evaluates a pipeline provided at runtime.

````
<p:run
  name? = NCName
  p:pipeline? = NCName>
    (p:input | 
     p:with-option | 
     p:log)*
</p:run>
````

The `p:run` step functions mostly like an atomic step in that you can define inputs connections and option values for it. However, unlike atomic steps, it has no defined signature. Any inputs are allowed and any outputs may be connected.

One input port is specificaly designated the pipeline input port. By default, that port is named `pipeline`, but its name can be changed by specifying a different name in the `p:pipeline` option.[1]

The pipeline input port must be connected. It is a static error (XSxxxx) if the pipeline port is not connected. The `p:run` step expects a single pipeline document on the pipeline port. It is a dynamic error (XDxxxx) if the input document is not a pipeline.

The pipeline that appears on the pipeline port is evaluated using the inputs and options specified on the `p:run` step. It is a dynamic error (XDxxxx) if the pipeline has inputs that are not specified on the `p:run` step. It is also a dynamic error (XDxxxx) if the pipeline has required options that are not specifed on the `p:run` step.

The outputs of the pipeline appear on the correspondingly named output ports of the `p:run` step. If the pipeline has an output is not bound on the `p:run` step, that output is discarded. If the `p:run` step has an output port that is not provided by the pipeline, an empty sequence appears on that port.

The `p:run` step is assumed to have a primary output port. If the pipeline evaluated does not have a primary output port, an empty sequence appears on that port.[2]

--

[1] The use of the qualified name p:pipeline is intentional, it avoids the possibility of collision with an option named `pipeline` in the evaluated pipeline.

[2]  Alternatively, that could be a dynamic error.

**Comment by xml-project** [comment]
This is pretty cool. I think that should solve most (if not all) expectation on dynamic pipeline execution.

For development purposes it might be useful to have an additional option "strict" as xs:boolean, default set to false. If it is set to true, a dynamic error is raised, if an input port is provided, that is not declared in the pipeline.

**Comment by vojtechtoman** [comment]
Nice. But how is this supposed to work with regard to static input/output port connection checking and the construction of the dependency graph in general? The fact that `p:run` step has a primary output port only helps if you rely on implicit connections:
```xml
...
<p:run>...</p:run>
<p:identity/>
...
```
If you don't use implicit connections, the processor really doesn't know if the output ports of `p:run` that you refer to in `p:pipe` exist and which of them is the primary one. How would the processor check whether the primary output port is connected (`err:XS0005`) in the following example?
```xml
...
<p:run name="run">...</p:run>
<p:identity>
  <p:input port="source">
    <p:pipe step="run" port="foo"/>
  </p:input>
</p:identity>
...
```
Something else: It appears that `p:run` is not a normal atomic step but a special construct like `p:viewport`, `p:choose` etc. The fact that the output ports of `p:run` are defined in the pipeline to be evaluated makes `p:run` kind of similar to the multi-container steps (`p:choose`, `p:try`). So it would be nice to keep the `p:run` output port story consistent with the recent thinking about the output ports of multi-container steps.

**Comment by ndw** [comment]
I think my little syntax fragment at the top is incomplete. You need to specify the outputs as well.

````
<p:run
  name? = NCName
  p:pipeline? = NCName>
    (p:input | p:output | 
     p:with-option | 
     p:log)*
</p:run>
````

**Comment by vojtechtoman** [comment]
OK, thanks. But if you have to specify the outputs, why is 'The `p:run` step is assumed to have a primary output port.' necessary? Why can't `p:run` use the usual rules for deciding which port is primary? I can imagine a `p:run` with no output ports, or with multiple output ports, all of which are non-primary.

**Comment by ndw** [comment]
Yes, that's plausible.

**Comment by gimsieke** [comment]
see also the [workshop minutes](https://github.com/xproc/Workshop-2017-09/wiki/Agenda-and-Minutes#prun) (yes, there is a circular reference back to this issue)
