### ISSUE TITLE
Serialization parameters

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#975]
Concerning the serialization parameters we say in [16.3.1.1. Serialization method ](https://spec.xproc.org/master/head/xproc/#serialization-method)(last bullet point):

> Parameter omit-xml-declaration is set to true.

In the very next section the third bullet point reads:

> The omit-xml-declaration must be supported. If the value is not specified or has the value no, an XML declaration must be produced.

I am not sure I understand, why this is not contradictory.

**Comment by Gertone** [comment]
I strongly prefer the second one actually because that is in line with XSLT.

Doing some research on this this morning, I was surprised to see that Saxon shifted gear over the years. 

On this  
```
<xsl:output
 omit-xml-declaration="yes" encoding="ISO-8859-1"/>
```
Saxon 6.5 on an XSLT 1.0 would have ignored the omit and still created a declaration
Saxon 9.9 does both... so it creates XML files that are not wellformed
It is a pity, but acceptable since the developer explicitly tells the processor to do the wrong things

If we would have the default differently in XProc
This
```
<p:with-option name="serialization" select="map{'indent' : true(),
  'encoding' : 'ISO-8859-1'}"/>
```
would be the same as
```
<p:with-option name="serialization" select="map{'indent' : true(), 
  'omit-xml-declaration': true(), 'encoding' : 'ISO-8859-1'}"/>
```
And the developer would tell the processor to create erroneous files without maybe realizing

So, I am in favor to set the default to "no"

On top, I would suggest that it would be a static error to do this
```
<p:with-option name="serialization" select="map{'indent' : true(), 
  'omit-xml-declaration': true(), 'encoding' : 'ISO-8859-1'}"/>
```
or it would raise a warning that this might lead to erroneous files,
or the processor could ignore the omit as Saxon used to do until recently

**Comment by xml-project** [comment]
I would propose the following changes: In "16.3.1.1" we change

> Parameter omit-xml-declaration is set to true.

To

> Parameter omit-xml-declaration is set to false.

And in 16.3.1.2 on the third bullet point we say

> The omit-xml-declaration must be supported. 

i.e. removing the contradictory sentence completely. This seems to make sense to me because the heading is "Minimal conformance", so it should not deal with default settings, should it?

**Comment by Gertone** [comment]
About the potential warning...

I dropped a question on the Saxonica issue list (https://saxonica.plan.io/issues/4574) and the response to that reads  (Michael Kay):

> I think this combination is deliberately permitted because the main purpose of omit-xml-declaration (the reason it was introduced) is to allow the serializer to emit fragments of XML which can be stitched together into a complete document by some other process, and in this use case you might well want to request an encoding other than UTF-8.

So, allowing a 'broken' intermediate state for this reason makes sense in an XSLT context. I would argue that in a pipeline orchestration context the "stitched together" would usually also be part of the pipeline. As such there might be less chance that a conflicting serialisation is "on purpose". I still tend to suggest a warning

**Comment by ndw** [comment]
I concur with @xml-project. In retrospect, the option "omit-xml-declaration" is too similar to "emit-xml-declaration" which would have exactly the opposite meaning. In fact, I wonder if that's how the contradictory text got into the spec.

For XML, I think omit-xml-declaration should be false. For HTML, I'm less sure. Certainly with `html-version` = 5, I would not expect an XML declaration to be produced regardless of the setting.

Also, is it a bug that we don't mention the `html-version` serialization parameter at all?
