### ISSUE TITLE
Clarify whether a dependency is established between two steps if the following step could possibly use a port of the preceding as DRP

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-specification#995]
see the discussion on [Twitter](https://twitter.com/gimsieke/status/1301540216688214016)

The paragraph above [this anchor](https://spec.xproc.org/master/head/xproc/#err.inline.D0001.5) reads: 

> If collection is true, the context item for the expression is undefined. Otherwise, the context item for the expression comes from the document connections, if they are specified. If they are not specified, the context item comes from the default readable port of the step. If no default readable port exists, the context item is undefined.

I understand Achim [as asserting](https://twitter.com/xml_project/status/1301535240607891456) that a dependency will only be established if an option actually refers to the context item.

I wonder which is true. Maybe we should state it more explicitly?

**Comment by xml-project** [comment]
> I understand Achim as asserting that a dependency will only be established if an option actually refers to the context item.

Right. But it is not only true for construction with `@collection=true`, but applies to all XPath expression.

Otherwise the whole section on [parallelism](https://spec.xproc.org/lastcall-2020-08/head/xproc/#parallelism) makes no sense.

> Maybe we should state it more explicitly?

I agree: Having parallelism of unconnected steps speeds up pipeline execution a lot. Making potentially connected steps actually connected would take away almost any parallelism. Since all almost all steps have primary output port and almost all steps have options (which **could** use the primary output port as context item), almost all pipelines would form a straight line of execution.

**Comment by xml-project** [comment]
@ndw 

1.  I do not think that a processor is required to do so, but it may.
2. To my understanding the order of execution is determined by the flow of documents. If you change `count(/*)`to `3+4` you change the flow because you take away the consumer.
3. The concept of "order of execution" (as opposite from the flow of documents) to my reading only comes into play when we look at side-effects as interacting with the file system.
4. Doing away almost any chance of having parallelism is not especially appealing to me.

**Comment by xml-project** [comment]
On a second thought: The problem @dmj raised with
````
<p:file-delete />
<p:file-mkdir />
````
is not totally connected to the question of context item. Suppose:
````
<p:file-mkdir href="apath" />
````
There is just a string in `href`, so there is no context-item. But if I write
````
<p:file-mkdir>
  <p:with-option name="href" select="'apath'" />
</p:file-mkdir>
````
there is one. So in the first case it is not guaranted that mkdir is executed after deleted, but in the second case it would be guaranteed. That seems strange to me (to say the least).

My conclusion: If we want file steps to be executed in the written order (and not in the order of connection), we need another tool than stipulating, that the connection between an XPath expression in step B and a primary output port in step A guarantees, that B runs after A. Did I miss something?

**Comment by ndw** [comment]
I thought the default context item for all "shortcut options" was the DRP. Consider:
```
<p:file-mkdir href="test{count(//*)}"/>
```
If you need to be explicit about it, we have the depends attribute, don't we?

**Comment by gimsieke** [comment]
> Suppose:
> 
> ```
> <p:file-mkdir href="apath" />
> ```
> 
> There is just a string in `href`, so there is no context-item. But if I write
> 
> ```
> <p:file-mkdir>
>   <p:with-option name="href" select="'apath'" />
> </p:file-mkdir>
> ```
> 
> there is one. So in the first case it is not guaranted that mkdir is executed after deleted, but in the second case it would be guaranteed. That seems strange to me (to say the least).

These cases are equivalent, the first one being a [syntactic shortcut](https://spec.xproc.org/master/head/xproc/#option-shortcut) (“The context node for the attribute value template comes from the default readable port for the step on which they occur.”). 

In both cases there is a context item if there is a DRP that provides one.

**Comment by xml-project** [comment]
But there is no AVT, is it?

**Comment by gimsieke** [comment]
As I understand the spec, an [AVT](https://spec.xproc.org/master/head/xproc/#dt-attribute-value-template) isn’t defined as an expression with curly braces around it but as the attribute that may contain these expressions in curly braces. At least it seems to be used in that sense in the section about syntactic shortcuts, since they only make a distinction between map attributes and AVTs.

**Comment by xml-project** [comment]
I am sorry, but that cherry picking is getting absurd.

**Comment by gimsieke** [comment]
This is no cherry picking, I’m just trying to cite relevant parts of the spec to say that `p:with-option` is (by and large, at least for the issue that is important here, which is the possibility to consume the DRP) equivalent to options-as-attributes.

**Comment by gimsieke** [comment]
> Having parallelism of unconnected steps speeds up pipeline execution a lot. Making potentially connected steps actually connected would take away almost any parallelism. Since all almost all steps have primary output port and almost all steps have options (which **could** use the primary output port as context item), almost all pipelines would form a straight line of execution.
Will parallelism be really dead if also “potentially-DRP-consuming” options establish a dependency? 

How often will it happen that a pipeline author uses steps in a subpipeline that don’t have a primary input? If they do so and they want to benefit from parallel execution, they can still insert `p:sink`s between the steps so that no DRP is available to the subsequent step. But my guess is that more often than not, pipeline authors think that a `p:file-copy` will be executed after a preceding (in document order) `p:file-mkdir`. So a dependency that is established between any option of the subsequent step and its DRP will help them avoid using `depends` explicitly. But maybe we need not speculate which happens more frequently. There are means to establish explicit dependencies (`@depends`) and there are means to avoid implicit dependencies (`p:sink`).

As I said, there are relatively few steps without a primary input (not only among the steps that we specified, but also in many real-life pipelines). However, a scenario that happens more frequently is that the primary input of the subsequent step is connected to another step’s output port that is not the DRP. If the preceding step has a primary output and the subsequent step has options that don’t refer to the context item, and you really want to avoid a dependency between the preceding and the subsequent step, then use a `p:sink` between them.

Apart from that, if the pipeline author forgets to insert `p:sink`s (at the relatively few places where it can make a difference), they will still benefit from parallel execution in `p:for-each`, which IMHO is the more relevant use case by far.

Of the two proposals, 

A) a dependency is only established if an option refers to the context item

B) a dependency is established if an option could refer to the context item

I prefer B). It puts less burden on an implementation to inspect XPath expressions, and it might be less surprising to pipeline authors.

But if we agree on A), it’s perfectly fine. All I’m saying is we need to explicitly specify it because it has significant implications on interoperability.

**Comment by gimsieke** [comment]
Additional thought: If the DRP provides multiple documents, referring to the content item is an error. In this case, one would use `p:with-option/p:empty` in order to explicitly prevent the option from possibly looking at the context item. Otherwise it is an error, irrespective of whether the option expression (given by `p:with-option` or AVT) refers to the context item or not. I’d argue that this corroborates proposal B above. As I said, in order to dissolve the dependency graph connection, one could use `p:sink` or, this I didn’t mention so far, `p:with-option/p:empty`. I don’t think it’s too much of a burden since people need to do the same if multiple documents arrive on the DRP.

**Comment by ndw** [comment]
This issue asks, roughly, whether implicit connections to the default readable port from step options constitute a dependency between steps. Consider:

```xml
<p:identity name="A">
  <p:with-input port="source">
    <doc/>
  </p:with-input>
</p:identity>

<p:http-request name="B" href="http://example.com/{3+4}"/>
```

The `href` attribute here is an option shortcut and the context item for value templates in that shortcut is the document on the default readable port.

So this fragment imposes a dependency between A and B such that A must be run first.

Observation 1: this sort of implicit dependency is common in XProc. Most steps have a primary output port and most steps have options. So one consequence of this rule is that parallelism is relatively tedious to achieve in XProc and will consequently be relatively uncommon.

(Although I put an AVT in that example for emphasis, I believe the current rules apply to that option even when it doesn’t contain an AVT at all.)

We have already established that a pipeline processor must parse all of the XPath expressions in options (whether shortcuts or not). This is a necessary consequence of the “variables anywhere” change; the processor needs to identify all variable references in order to build the graph.

Observation 2: given that the processor has to determine if there are variable references in an expression, it is not at all difficult to determine if the context item is referenced.

This leads to the disagreement that plays out in this issue. The processor knows that the expression that initializes `href` does not refer to the context item, so why not ignore that implicit edge? The resulting pipeline could run those two steps in parallel and it cannot make any difference to the results.

We’re attempting to define a declarative, functional language. In the absence of side effects, the processor should be able to reorder steps and run steps in parallel as long as the relationship “if B consumes the output of A, A will run before B” is preserved.

Observation 3: relying on the initialization of an option, especially one where the initializing expression doesn’t even refer to the context item, as a mechanism for guaranteeing that A runs before B (because the author knows that A has a side effect) is a fairly subtle and tenuous mechanism. We have an explicit mechanism for this purpose that is robust and clear: the depends attribute.

This issue frames the discussion as being about the implicit connection to the default readable port that arises when an option has no explicit binding for the context item. In that context, one where a significant distinction is being drawn between implicit and explicit bindings, I’m opposed to making the implicit case different from the explicit case.

However.

I had a chat with Achim the other day about this issue and I think I understand his position better. It is in one sense more radical than I realized, but also much more consistent.

One advantage of a declarative, functional language is that it gives the compiler a lot of leeway to optimize the execution of the program. Variables that are never used don’t have to be initialized, for example. Functions that are never called don’t have to be preserved in the compiled form. And function arguments that aren’t referenced can be ignored.

Consider a function definition and its call in some imaginary functional language:

```
  def f = function(a, b) {
               return a;
             }

   x = f(1,2)
```

Absent any other context, the compiler is free to ignore “b” in the definition of the function and ignore “2” in the call. It can compile this to “`x = f(1)`”. In fact, an optimizing compiler would very likely compile this to “`x = 1`”.

Now consider this pipeline:

```xml
<p:identity name="A"/>
<p:identity name="B"/>
<p:identity name="C"/>
```

Steps B and C cannot have any effect. Any connections to B and C could be rewritten as connections to A and steps B and C could be removed. I think processors should be free to do this.

With that preamble out of the way, a proposal: a pipeline processor can discard any edge that it knows is not used. In other words, not only can the edge between A and B in the initial example in this message be ignored, it can be ignored in this example as well:

```xml
<p:identity name="A">
  <p:with-input port="source">
    <doc/>
  </p:with-input>
</p:identity>

<p:http-request name="B">
  <p:with-option name="href"
                 select="concat('http://example.com/', (3+4))"/>
    <p:pipe step="A" port="result"/>
  </p:with-option>
</p:http-request>
```

Unlike my previous understanding of this issue, this rule treats implicit and explicit connections equally: if the processor can determine that a connection has no consequence, it can remove that connection from the graph.

While it’s possible that this will lead to surprising behavior, I think that’s going to be very, very uncommon in practice, and it won’t require the pipeline author to know something magic about the difference between implicit and explicit connections.

1. It’s consistent.
2. It greatly increases the parallelism of pipelines.
3. Authors can still use the `depends` attribute to impose an order when side effects are involved.

**Comment by xatapult** [comment]
Kudos for this long but clear explanation and analysis. I agree with your conclusion.

(But it would mean that the section about `@depends` in the book should have been longer... :grin:)

**Comment by gimsieke** [comment]
Do we need to clarify that a processor may disregard only edges that it _statically_ determines to be unused? I think so.

Otherwise, I’m fine with this resolution.

**Comment by ndw** [comment]
15 July 2021, the editors are inclined to go with the proposal Norm outlined above; an implementation may statically remove any edges that it can prove will never be used. If the DRP from step A to step B is never used by step B, then the "edge" in the graph connecting A and B along that DRP can be removed "at compile time."
